-- Table: dbo.BANNERS
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'BANNERS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.BANNERS
    (
        BANNER_ID     BIGINT IDENTITY(1,1) NOT NULL,
        TITLE_EN      NVARCHAR(150)        NULL,
        TITLE_AR      NVARCHAR(150)        NULL,
        ALT_TEXT_EN   NVARCHAR(250)        NULL,
        ALT_TEXT_AR   NVARCHAR(250)        NULL,
        IMAGE_URL     VARCHAR(500)         NOT NULL,
        LINK_TYPE     VARCHAR(20)          NOT NULL, -- 'NONE', 'PRODUCT', 'CATEGORY', 'OFFER', 'EXTERNAL'
        PRODUCT_ID    BIGINT               NULL,
        CATEGORY_ID   BIGINT               NULL,
        OFFER_ID      BIGINT               NULL,
        EXTERNAL_URL  VARCHAR(500)         NULL,
        START_AT      DATETIME2            NOT NULL,
        END_AT        DATETIME2            NOT NULL,
        IS_ACTIVE     BIT                  NOT NULL CONSTRAINT DF_BANNERS_IS_ACTIVE DEFAULT (1),
        CREATED_BY    BIGINT               NULL,
        CREATED_AT    DATETIME2            NOT NULL CONSTRAINT DF_BANNERS_CREATED DEFAULT (SYSUTCDATETIME()),
        UPDATED_BY    BIGINT               NULL,
        UPDATED_AT    DATETIME2            NULL,
        IS_DELETED    BIT                  NOT NULL CONSTRAINT DF_BANNERS_IS_DELETED DEFAULT (0),
        DELETED_AT    DATETIME2            NULL,

        CONSTRAINT PK_BANNERS PRIMARY KEY CLUSTERED (BANNER_ID),
        CONSTRAINT FK_BANNERS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCTS (PRODUCT_ID),
        CONSTRAINT FK_BANNERS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES dbo.CATEGORIES (CATEGORY_ID)
    );

    CREATE NONCLUSTERED INDEX IX_BANNERS_ACTIVE_SCHEDULE
        ON dbo.BANNERS (IS_ACTIVE, IS_DELETED, START_AT, END_AT);
END;
GO
