-- TABLE: dbo.CART_ITEM_CUSTOMIZATIONS
-- Description: Stores customization options selected for a specific cart line item.

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CART_ITEM_CUSTOMIZATIONS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.CART_ITEM_CUSTOMIZATIONS
    (
        CART_ITEM_CUSTOMIZATION_ID BIGINT IDENTITY(1,1) NOT NULL,
        CART_ITEM_ID               BIGINT               NOT NULL,
        DOC_NO                     VARCHAR(50)          NOT NULL,
        CUSTOMIZATION_OPTION_ID    BIGINT               NOT NULL,
        SELECTED_VALUE             DECIMAL(18,3)        NULL,
        CREATED_AT                 DATETIME2            NOT NULL CONSTRAINT DF_CART_ITEM_CUST_CREATED DEFAULT (SYSUTCDATETIME()),

        CONSTRAINT PK_CART_ITEM_CUSTOMIZATIONS PRIMARY KEY CLUSTERED (CART_ITEM_CUSTOMIZATION_ID),
        CONSTRAINT FK_CART_ITEM_CUST_ITEM FOREIGN KEY (CART_ITEM_ID) REFERENCES dbo.CART_ITEMS (CART_ITEM_ID) ON DELETE CASCADE,
        CONSTRAINT FK_CART_ITEM_CUST_OPTION FOREIGN KEY (CUSTOMIZATION_OPTION_ID) REFERENCES dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_OPTION_ID)
    );

    -- Unique Constraint: (CART_ITEM_ID, CUSTOMIZATION_OPTION_ID) prevents duplicate options on same item
    CREATE UNIQUE NONCLUSTERED INDEX UX_CART_ITEM_CUSTOMIZATIONS
        ON dbo.CART_ITEM_CUSTOMIZATIONS (CART_ITEM_ID, CUSTOMIZATION_OPTION_ID);
END;
GO
