-- TABLE: dbo.CART_ITEMS
-- Description: Stores products, quantity, instructions, item status, and signature for active carts.

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CART_ITEMS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.CART_ITEMS
    (
        CART_ITEM_ID         BIGINT IDENTITY(1,1) NOT NULL,
        CART_ID              BIGINT               NOT NULL,
        DOC_NO               VARCHAR(50)          NOT NULL,
        PRODUCT_ID           BIGINT               NOT NULL,
        QUANTITY             INT                  NOT NULL CONSTRAINT DF_CART_ITEMS_QTY DEFAULT (1),
        CUSTOM_DATA          NVARCHAR(500)        NULL,
        SPECIAL_INSTRUCTIONS NVARCHAR(1000)       NULL,
        ITEM_STATUS          VARCHAR(20)          NOT NULL CONSTRAINT DF_CART_ITEMS_STATUS DEFAULT ('ACTIVE'),
        ITEM_SIGNATURE       VARCHAR(100)         NOT NULL,
        CREATED_AT           DATETIME2            NOT NULL CONSTRAINT DF_CART_ITEMS_CREATED DEFAULT (SYSUTCDATETIME()),
        UPDATED_AT           DATETIME2            NULL,

        CONSTRAINT PK_CART_ITEMS PRIMARY KEY CLUSTERED (CART_ITEM_ID),
        CONSTRAINT FK_CART_ITEMS_CART FOREIGN KEY (CART_ID) REFERENCES dbo.CARTS (CART_ID) ON DELETE CASCADE,
        CONSTRAINT FK_CART_ITEMS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCTS (PRODUCT_ID),
        CONSTRAINT CK_CART_ITEMS_QUANTITY CHECK (QUANTITY > 0)
    );

    -- Unique Constraint: (CART_ID, ITEM_SIGNATURE) to enforce signature line merging
    CREATE UNIQUE NONCLUSTERED INDEX UX_CART_ITEMS_SIGNATURE
        ON dbo.CART_ITEMS (CART_ID, ITEM_SIGNATURE);

    CREATE NONCLUSTERED INDEX IX_CART_ITEMS_STATUS
        ON dbo.CART_ITEMS (ITEM_STATUS);
END;
GO
