-- =============================================================================
-- TABLE: dbo.CATEGORIES
-- Description: Hierarchical product categories with parent-child support,
--              bilingual names (EN/AR), display ordering, and visibility.
-- =============================================================================

CREATE TABLE dbo.CATEGORIES
(
    CATEGORY_ID         BIGINT IDENTITY(1,1) NOT NULL,
    PARENT_CATEGORY_ID  BIGINT NULL,
    CATEGORY_CODE       VARCHAR(50) NULL,
    CATEGORY_NAME_EN    VARCHAR(150) NOT NULL,
    CATEGORY_NAME_AR    NVARCHAR(150) NULL,
    DESCRIPTION_EN      VARCHAR(500) NULL,
    DESCRIPTION_AR      NVARCHAR(500) NULL,
    IMAGE_URL           VARCHAR(500) NULL,
    DISPLAY_ORDER       INT NOT NULL DEFAULT 0,
    IS_ACTIVE           BIT NOT NULL DEFAULT 1,
    IS_VISIBLE          BIT NOT NULL DEFAULT 1,
    CREATED_AT          DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT          DATETIME2 NULL,

    CONSTRAINT PK_CATEGORIES PRIMARY KEY CLUSTERED (CATEGORY_ID),
    CONSTRAINT FK_CATEGORIES_PARENT FOREIGN KEY (PARENT_CATEGORY_ID) 
        REFERENCES dbo.CATEGORIES (CATEGORY_ID)
);

CREATE NONCLUSTERED INDEX IX_CATEGORIES_PARENT 
    ON dbo.CATEGORIES (PARENT_CATEGORY_ID) 
    WHERE PARENT_CATEGORY_ID IS NOT NULL;

CREATE UNIQUE NONCLUSTERED INDEX IX_CATEGORIES_CODE 
    ON dbo.CATEGORIES (CATEGORY_CODE) 
    WHERE CATEGORY_CODE IS NOT NULL;

CREATE NONCLUSTERED INDEX IX_CATEGORIES_DISPLAY_ORDER 
    ON dbo.CATEGORIES (DISPLAY_ORDER, IS_ACTIVE, IS_VISIBLE);
GO
