-- TABLE: dbo.COUPONS
-- Description: Stores customer-entered promotional coupon codes.

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'COUPONS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.COUPONS
    (
        COUPON_ID            BIGINT IDENTITY(1,1) NOT NULL,
        COUPON_CODE          VARCHAR(50)          NOT NULL,
        DISCOUNT_TYPE        VARCHAR(20)          NOT NULL, -- 'PERCENTAGE' or 'FLAT'
        DISCOUNT_VALUE       DECIMAL(18,2)        NOT NULL,
        MAX_DISCOUNT_AMOUNT  DECIMAL(18,2)        NULL,
        MINIMUM_ORDER_AMOUNT DECIMAL(18,2)        NOT NULL CONSTRAINT DF_COUPONS_MIN_AMT DEFAULT (0.00),
        VALID_FROM           DATETIME2            NOT NULL,
        VALID_TO             DATETIME2            NOT NULL,
        USAGE_LIMIT_TOTAL    INT                  NULL,
        USAGE_LIMIT_PER_USER INT                  NULL,
        COUPON_STATUS        VARCHAR(20)          NOT NULL CONSTRAINT DF_COUPONS_STATUS DEFAULT ('ACTIVE'), -- 'ACTIVE', 'INACTIVE'
        COUPON_DESC          NVARCHAR(500)        NULL,
        CREATED_BY           BIGINT               NULL,
        CREATED_AT           DATETIME2            NOT NULL CONSTRAINT DF_COUPONS_CREATED DEFAULT (SYSUTCDATETIME()),
        UPDATED_BY           BIGINT               NULL,
        UPDATED_AT           DATETIME2            NULL,
        IS_DELETED           BIT                  NOT NULL CONSTRAINT DF_COUPONS_IS_DELETED DEFAULT (0),
        DELETED_AT           DATETIME2            NULL,

        CONSTRAINT PK_COUPONS PRIMARY KEY CLUSTERED (COUPON_ID),
        CONSTRAINT UQ_COUPONS_CODE UNIQUE NONCLUSTERED (COUPON_CODE)
    );

    CREATE NONCLUSTERED INDEX IX_COUPONS_STATUS
        ON dbo.COUPONS (COUPON_CODE, COUPON_STATUS, IS_DELETED);
END;
GO
