-- TABLE: dbo.COUPON_USAGES
-- Description: Stores successful coupon redemptions and reversals.

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'COUPON_USAGES' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.COUPON_USAGES
    (
        COUPON_USAGE_ID  BIGINT IDENTITY(1,1) NOT NULL,
        COUPON_ID        BIGINT               NOT NULL,
        CUSTOMER_USER_ID BIGINT               NOT NULL,
        ORDER_ID         BIGINT               NOT NULL,
        USAGE_STATUS     VARCHAR(20)          NOT NULL CONSTRAINT DF_COUPON_USAGES_STATUS DEFAULT ('USED'), -- 'USED', 'REVERSED'
        USED_AT          DATETIME2            NOT NULL CONSTRAINT DF_COUPON_USAGES_USED DEFAULT (SYSUTCDATETIME()),
        REVERSED_AT      DATETIME2            NULL,

        CONSTRAINT PK_COUPON_USAGES PRIMARY KEY CLUSTERED (COUPON_USAGE_ID),
        CONSTRAINT UQ_COUPON_USAGES_ORDER UNIQUE NONCLUSTERED (ORDER_ID),
        CONSTRAINT FK_COUPON_USAGES_COUPON FOREIGN KEY (COUPON_ID) REFERENCES dbo.COUPONS (COUPON_ID),
        CONSTRAINT FK_COUPON_USAGES_CUSTOMER FOREIGN KEY (CUSTOMER_USER_ID) REFERENCES dbo.CUSTOMER_USERS (USER_ID),
        CONSTRAINT FK_COUPON_USAGES_ORDER FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDERS (ORDER_ID)
    );

    CREATE NONCLUSTERED INDEX IX_COUPON_USAGES_COUPON_USER
        ON dbo.COUPON_USAGES (COUPON_ID, CUSTOMER_USER_ID, USAGE_STATUS);
END;
GO
