-- =============================================================================
-- TABLE: dbo.CUSTOMER_WISHLISTS
-- Description: Stores customer favorite/wishlist products.
-- =============================================================================

CREATE TABLE dbo.CUSTOMER_WISHLISTS
(
    WISHLIST_ID         BIGINT IDENTITY(1,1) NOT NULL,
    CUSTOMER_USER_ID    BIGINT NOT NULL,
    PRODUCT_ID          BIGINT NOT NULL,
    CREATED_AT          DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT PK_CUSTOMER_WISHLISTS PRIMARY KEY CLUSTERED (WISHLIST_ID),
    CONSTRAINT FK_CUSTOMER_WISHLISTS_USER FOREIGN KEY (CUSTOMER_USER_ID) 
        REFERENCES dbo.CUSTOMER_USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CUSTOMER_WISHLISTS_PRODUCT FOREIGN KEY (PRODUCT_ID) 
        REFERENCES dbo.PRODUCTS (PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_CUSTOMER_WISHLISTS_USER_PRODUCT UNIQUE NONCLUSTERED (CUSTOMER_USER_ID, PRODUCT_ID)
);

CREATE NONCLUSTERED INDEX IX_CUSTOMER_WISHLISTS_USER 
    ON dbo.CUSTOMER_WISHLISTS (CUSTOMER_USER_ID, PRODUCT_ID);
GO
