-- =============================================================================
-- TABLE: dbo.CUSTOMIZATION_OPTIONS
-- Description: Selectable options inside each customization group
-- =============================================================================

CREATE TABLE dbo.CUSTOMIZATION_OPTIONS
(
    CUSTOMIZATION_OPTION_ID BIGINT IDENTITY(1,1) NOT NULL,
    CUSTOMIZATION_GROUP_ID  BIGINT NOT NULL,
    OPTION_CODE             VARCHAR(50) NOT NULL,
    OPTION_NAME_EN          NVARCHAR(150) NOT NULL,
    OPTION_NAME_AR          NVARCHAR(150) NOT NULL,
    PRICING_VALUE           DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    IS_ACTIVE               BIT NOT NULL DEFAULT 1,
    CREATED_AT              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT              DATETIME2 NULL,

    CONSTRAINT PK_CUSTOMIZATION_OPTIONS PRIMARY KEY CLUSTERED (CUSTOMIZATION_OPTION_ID),
    CONSTRAINT FK_CUSTOMIZATION_OPTIONS_GROUP FOREIGN KEY (CUSTOMIZATION_GROUP_ID) 
        REFERENCES dbo.CUSTOMIZATION_GROUPS (CUSTOMIZATION_GROUP_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_CUSTOMIZATION_OPTIONS_GROUP_CODE UNIQUE NONCLUSTERED (CUSTOMIZATION_GROUP_ID, OPTION_CODE)
);

CREATE NONCLUSTERED INDEX IX_CUSTOMIZATION_OPTIONS_GROUP 
    ON dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, IS_ACTIVE);
GO
