IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OFFERS]') AND type in (N'U'))
BEGIN
    CREATE TABLE dbo.OFFERS
    (
        OFFER_ID             BIGINT IDENTITY(1,1) NOT NULL,
        OFFER_TITLE_EN       NVARCHAR(200) NOT NULL,
        OFFER_TITLE_AR       NVARCHAR(200) NOT NULL,
        DISCOUNT_TYPE        NVARCHAR(50) NOT NULL, -- FLAT, PERCENTAGE
        DISCOUNT_VALUE       DECIMAL(18,2) NOT NULL,
        MINIMUM_ORDER_AMOUNT DECIMAL(18,2) NULL,
        MAX_DISCOUNT_AMOUNT  DECIMAL(18,2) NULL,
        START_AT             DATETIME2 NOT NULL,
        END_AT               DATETIME2 NOT NULL,
        IS_ACTIVE            BIT NOT NULL DEFAULT(1),
        CREATED_BY           BIGINT NULL,
        CREATED_AT           DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
        UPDATED_BY           BIGINT NULL,
        UPDATED_AT           DATETIME2 NULL,
        IS_DELETED           BIT NOT NULL DEFAULT(0),
        DELETED_AT           DATETIME2 NULL,
        CONSTRAINT PK_OFFERS PRIMARY KEY CLUSTERED (OFFER_ID ASC)
    );
END;
GO
