IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OFFER_SCOPES]') AND type in (N'U'))
BEGIN
    CREATE TABLE dbo.OFFER_SCOPES
    (
        SCOPE_ID    BIGINT IDENTITY(1,1) NOT NULL,
        OFFER_ID    BIGINT NOT NULL,
        SCOPE_TYPE  NVARCHAR(50) NOT NULL, -- ALL, CATEGORY, PRODUCT
        CATEGORY_ID BIGINT NULL,
        PRODUCT_ID  BIGINT NULL,
        CREATED_AT  DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_OFFER_SCOPES PRIMARY KEY CLUSTERED (SCOPE_ID ASC),
        CONSTRAINT FK_OFFER_SCOPES_OFFERS FOREIGN KEY (OFFER_ID) REFERENCES dbo.OFFERS (OFFER_ID) ON DELETE CASCADE,
        CONSTRAINT FK_OFFER_SCOPES_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES dbo.CATEGORIES (CATEGORY_ID),
        CONSTRAINT FK_OFFER_SCOPES_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCTS (PRODUCT_ID)
    );
END;
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_OFFER_SCOPE_CATEGORY' AND object_id = OBJECT_ID('dbo.OFFER_SCOPES'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_OFFER_SCOPE_CATEGORY 
    ON dbo.OFFER_SCOPES (OFFER_ID, CATEGORY_ID) 
    WHERE CATEGORY_ID IS NOT NULL;
END;
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_OFFER_SCOPE_PRODUCT' AND object_id = OBJECT_ID('dbo.OFFER_SCOPES'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_OFFER_SCOPE_PRODUCT 
    ON dbo.OFFER_SCOPES (OFFER_ID, PRODUCT_ID) 
    WHERE PRODUCT_ID IS NOT NULL;
END;
GO
