-- =============================================================================
-- TABLE: dbo.PRODUCTS
-- Description: Core product catalog table containing product specifications,
--              bilingual names, Halal certification, nutrition, and storage info.
-- =============================================================================

CREATE TABLE dbo.PRODUCTS
(
    PRODUCT_ID                  BIGINT IDENTITY(1,1) NOT NULL,
    CATEGORY_ID                 BIGINT NOT NULL,
    DOC_NO                      VARCHAR(50) NOT NULL,
    DOC_TYPE                    VARCHAR(20) NOT NULL DEFAULT 'PROD',
    PRODUCT_NAME_EN             NVARCHAR(200) NOT NULL,
    PRODUCT_NAME_AR             NVARCHAR(200) NOT NULL,
    DESCRIPTION_EN              NVARCHAR(2000) NULL,
    DESCRIPTION_AR              NVARCHAR(2000) NULL,
    COUNTRY_OF_ORIGIN           NVARCHAR(100) NULL,
    IS_HALAL_CERTIFIED          BIT NOT NULL DEFAULT 1,
    HALAL_CERTIFICATE_NO        VARCHAR(100) NULL,
    HALAL_CERTIFICATE_URL       VARCHAR(500) NULL,
    NUTRITION_INFORMATION_EN    NVARCHAR(2000) NULL,
    NUTRITION_INFORMATION_AR    NVARCHAR(2000) NULL,
    STORAGE_INSTRUCTIONS_EN     NVARCHAR(1000) NULL,
    STORAGE_INSTRUCTIONS_AR     NVARCHAR(1000) NULL,
    IS_CUSTOMIZABLE             BIT NOT NULL DEFAULT 0,
    CUSTOMIZATION_TEMPLATE_ID   BIGINT NULL,
    DISPLAY_ORDER               INT NOT NULL DEFAULT 0,
    IS_FEATURED                 BIT NOT NULL DEFAULT 0,
    IS_BESTSELLER               BIT NOT NULL DEFAULT 0,
    IS_ACTIVE                   BIT NOT NULL DEFAULT 1,
    CREATED_AT                  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT                  DATETIME2 NULL,

    CONSTRAINT PK_PRODUCTS PRIMARY KEY CLUSTERED (PRODUCT_ID),
    CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (CATEGORY_ID) 
        REFERENCES dbo.CATEGORIES (CATEGORY_ID),
    CONSTRAINT UQ_PRODUCTS_DOC_NO UNIQUE NONCLUSTERED (DOC_NO)
);

CREATE NONCLUSTERED INDEX IX_PRODUCTS_CATEGORY 
    ON dbo.PRODUCTS (CATEGORY_ID, IS_ACTIVE);

CREATE NONCLUSTERED INDEX IX_PRODUCTS_FEATURED 
    ON dbo.PRODUCTS (IS_FEATURED, IS_ACTIVE) 
    WHERE IS_FEATURED = 1;

CREATE NONCLUSTERED INDEX IX_PRODUCTS_BESTSELLER 
    ON dbo.PRODUCTS (IS_BESTSELLER, IS_ACTIVE) 
    WHERE IS_BESTSELLER = 1;
GO
