-- =============================================================================
-- TABLE: dbo.PRODUCTS
-- Description: Core product catalog table matching exact Notion specification.
-- =============================================================================

CREATE TABLE dbo.PRODUCTS
(
    PRODUCT_ID                  BIGINT IDENTITY(1,1) NOT NULL,
    CATEGORY_ID                 BIGINT NOT NULL,
    DOC_NO                      VARCHAR(50) NOT NULL,
    DOC_TYPE                    VARCHAR(20) NOT NULL DEFAULT 'PROD',
    PRODUCT_NAME_EN             NVARCHAR(200) NOT NULL,
    PRODUCT_NAME_AR             NVARCHAR(200) NOT NULL,
    DESCRIPTION_EN              NVARCHAR(2000) NULL,
    DESCRIPTION_AR              NVARCHAR(2000) NULL,
    IS_CUSTOMIZABLE             BIT NOT NULL DEFAULT 0,
    CUSTOMIZATION_TEMPLATE_ID   BIGINT NULL,
    UNIT_ID                     INT NOT NULL,
    DISCOUNT_PERCENTAGE         DECIMAL(5,2) NOT NULL DEFAULT 0,
    STOCK_COUNT                 DECIMAL(18,3) NOT NULL DEFAULT 0,
    IS_ACTIVE                   BIT NOT NULL DEFAULT 1,
    IS_DELETED                  BIT NOT NULL DEFAULT 0,
    DELETED_AT                  DATETIME2 NULL,
    IS_FEATURED                 BIT NOT NULL DEFAULT 0,
    IS_PREORDERABLE             BIT NOT NULL DEFAULT 0,
    CREATED_AT                  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT                  DATETIME2 NULL,

    CONSTRAINT PK_PRODUCTS PRIMARY KEY CLUSTERED (PRODUCT_ID),
    CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (CATEGORY_ID) 
        REFERENCES dbo.CATEGORIES (CATEGORY_ID),
    CONSTRAINT FK_PRODUCTS_UNIT FOREIGN KEY (UNIT_ID) 
        REFERENCES dbo.MEASUREMENT_UNITS (UNIT_ID),
    CONSTRAINT UQ_PRODUCTS_DOC_NO UNIQUE NONCLUSTERED (DOC_NO)
);

CREATE NONCLUSTERED INDEX IX_PRODUCTS_CATEGORY 
    ON dbo.PRODUCTS (CATEGORY_ID, IS_ACTIVE);

CREATE NONCLUSTERED INDEX IX_PRODUCTS_FEATURED 
    ON dbo.PRODUCTS (IS_FEATURED, IS_ACTIVE) 
    WHERE IS_FEATURED = 1;
GO
