-- =============================================================================
-- TABLE: dbo.PRODUCT_PRICES
-- Description: Fixed or Per-Unit pricing for product weight options.
-- =============================================================================

CREATE TABLE dbo.PRODUCT_PRICES
(
    PRODUCT_PRICE_ID            BIGINT IDENTITY(1,1) NOT NULL,
    PRODUCT_ID                  BIGINT NOT NULL,
    PRODUCT_WEIGHT_OPTION_ID    BIGINT NOT NULL,
    PRICE_TYPE                  VARCHAR(20) NOT NULL DEFAULT 'FIXED', -- 'FIXED' or 'PER_UNIT'
    REGULAR_PRICE               DECIMAL(18,2) NOT NULL,
    DISCOUNT_PRICE              DECIMAL(18,2) NULL,
    CURRENCY_CODE               VARCHAR(10) NOT NULL DEFAULT 'AED',
    IS_ACTIVE                   BIT NOT NULL DEFAULT 1,
    CREATED_AT                  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT                  DATETIME2 NULL,

    CONSTRAINT PK_PRODUCT_PRICES PRIMARY KEY CLUSTERED (PRODUCT_PRICE_ID),
    CONSTRAINT FK_PRODUCT_PRICES_PRODUCT FOREIGN KEY (PRODUCT_ID) 
        REFERENCES dbo.PRODUCTS (PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PRODUCT_PRICES_WEIGHT_OPTION FOREIGN KEY (PRODUCT_WEIGHT_OPTION_ID) 
        REFERENCES dbo.PRODUCT_WEIGHT_OPTIONS (PRODUCT_WEIGHT_OPTION_ID)
);

CREATE NONCLUSTERED INDEX IX_PRODUCT_PRICES_WEIGHT_OPTION 
    ON dbo.PRODUCT_PRICES (PRODUCT_WEIGHT_OPTION_ID, IS_ACTIVE);
GO
