-- =============================================================================
-- TABLE: dbo.TEMPLATE_GROUP_MAPPING
-- Description: Bridge table mapping customization templates to reusable customization groups
-- =============================================================================

CREATE TABLE dbo.TEMPLATE_GROUP_MAPPING
(
    TEMPLATE_GROUP_MAPPING_ID   BIGINT IDENTITY(1,1) NOT NULL,
    CUSTOMIZATION_TEMPLATE_ID   BIGINT NOT NULL,
    CUSTOMIZATION_GROUP_ID      BIGINT NOT NULL,
    IS_ACTIVE                   BIT NOT NULL DEFAULT 1,
    CREATED_AT                  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT                  DATETIME2 NULL,

    CONSTRAINT PK_TEMPLATE_GROUP_MAPPING PRIMARY KEY CLUSTERED (TEMPLATE_GROUP_MAPPING_ID),
    CONSTRAINT FK_TEMPLATE_GROUP_MAPPING_TEMPLATE FOREIGN KEY (CUSTOMIZATION_TEMPLATE_ID) 
        REFERENCES dbo.CUSTOMIZATION_TEMPLATES (CUSTOMIZATION_TEMPLATE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TEMPLATE_GROUP_MAPPING_GROUP FOREIGN KEY (CUSTOMIZATION_GROUP_ID) 
        REFERENCES dbo.CUSTOMIZATION_GROUPS (CUSTOMIZATION_GROUP_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_TEMPLATE_GROUP_MAPPING UNIQUE NONCLUSTERED (CUSTOMIZATION_TEMPLATE_ID, CUSTOMIZATION_GROUP_ID)
);

CREATE NONCLUSTERED INDEX IX_TEMPLATE_GROUP_MAPPING_GROUP 
    ON dbo.TEMPLATE_GROUP_MAPPING (CUSTOMIZATION_GROUP_ID);
GO
