-- =============================================================================
-- TABLE: dbo.WISHLIST_ITEMS
-- Description: Detail table for products inside customer wishlists.
-- =============================================================================

CREATE TABLE dbo.WISHLIST_ITEMS
(
    WISHLIST_ITEM_ID    BIGINT IDENTITY(1,1) NOT NULL,
    WISHLIST_ID         BIGINT NOT NULL,
    PRODUCT_ID          BIGINT NOT NULL,
    ADDED_AT            DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT PK_WISHLIST_ITEMS PRIMARY KEY CLUSTERED (WISHLIST_ITEM_ID),
    CONSTRAINT FK_WISHLIST_ITEMS_WISHLIST FOREIGN KEY (WISHLIST_ID) 
        REFERENCES dbo.WISHLISTS (WISHLIST_ID) ON DELETE CASCADE,
    CONSTRAINT FK_WISHLIST_ITEMS_PRODUCT FOREIGN KEY (PRODUCT_ID) 
        REFERENCES dbo.PRODUCTS (PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_WISHLIST_ITEMS_WISHLIST_PRODUCT UNIQUE NONCLUSTERED (WISHLIST_ID, PRODUCT_ID)
);

CREATE NONCLUSTERED INDEX IX_WISHLIST_ITEMS_WISHLIST 
    ON dbo.WISHLIST_ITEMS (WISHLIST_ID, PRODUCT_ID);
GO
