-- =============================================================================
-- STORED PROCEDURE: dbo.PR_ADD_TO_CART
-- Description: Adds a product (with selected cut customization options and special instructions) to customer's active cart.
-- =============================================================================

CREATE OR ALTER PROCEDURE dbo.PR_ADD_TO_CART
(
    @CUSTOMER_USER_ID BIGINT,
    @PRODUCT_ID BIGINT,
    @QUANTITY INT = 1,
    @SPECIAL_INSTRUCTIONS NVARCHAR(1000) = NULL,
    @OPTION_IDS dbo.TT_CUSTOMIZATION_OPTION_IDS READONLY
)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    IF @CUSTOMER_USER_ID IS NULL OR @CUSTOMER_USER_ID <= 0
    BEGIN
        RAISERROR('Valid CustomerUserId is required.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMER_USERS WHERE USER_ID = @CUSTOMER_USER_ID)
    BEGIN
        RAISERROR('Customer user not found.', 16, 1);
        RETURN;
    END;

    IF @PRODUCT_ID IS NULL OR @PRODUCT_ID <= 0
    BEGIN
        RAISERROR('Valid ProductId is required.', 16, 1);
        RETURN;
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.PRODUCTS WHERE PRODUCT_ID = @PRODUCT_ID AND IS_DELETED = 0)
    BEGIN
        RAISERROR('Product not found or deleted.', 16, 1);
        RETURN;
    END;

    IF ISNULL(@QUANTITY, 0) <= 0
        SET @QUANTITY = 1;

    BEGIN TRANSACTION;

    BEGIN TRY
        DECLARE
            @CART_ID BIGINT = NULL,
            @CART_DOC_NO VARCHAR(50) = NULL,
            @ITEM_SIGNATURE VARCHAR(100) = NULL,
            @OPTION_STRING VARCHAR(80) = NULL,
            @EXISTING_CART_ITEM_ID BIGINT = NULL;

        -- 1. Get or Create ACTIVE Cart for Customer
        SELECT @CART_ID = CART_ID, @CART_DOC_NO = DOC_NO
        FROM dbo.CARTS
        WHERE CUSTOMER_USER_ID = @CUSTOMER_USER_ID AND CART_STATUS = 'ACTIVE';

        IF @CART_ID IS NULL
        BEGIN
            EXEC dbo.PR_GET_NEXT_DOC_NO
                @DOCTYPE = 'CRT1',
                @DOC_NO = @CART_DOC_NO OUTPUT;

            INSERT INTO dbo.CARTS (DOCTYPE, DOC_NO, CUSTOMER_USER_ID, CART_STATUS, CREATED_AT)
            VALUES ('CRT1', @CART_DOC_NO, @CUSTOMER_USER_ID, 'ACTIVE', SYSUTCDATETIME());

            SET @CART_ID = SCOPE_IDENTITY();
        END;

        -- 2. Build Item Signature from selected option IDs
        SELECT @OPTION_STRING = STRING_AGG(CAST(OPTION_ID AS VARCHAR(20)), '_') WITHIN GROUP (ORDER BY OPTION_ID)
        FROM (SELECT DISTINCT OPTION_ID FROM @OPTION_IDS) AS T;

        IF @OPTION_STRING IS NULL OR @OPTION_STRING = ''
            SET @ITEM_SIGNATURE = CAST(@PRODUCT_ID AS VARCHAR(20)) + '|NONE';
        ELSE
            SET @ITEM_SIGNATURE = CAST(@PRODUCT_ID AS VARCHAR(20)) + '|' + @OPTION_STRING;

        -- 3. Check if exact item signature exists in active cart
        SELECT @EXISTING_CART_ITEM_ID = CART_ITEM_ID
        FROM dbo.CART_ITEMS
        WHERE CART_ID = @CART_ID AND ITEM_SIGNATURE = @ITEM_SIGNATURE AND ITEM_STATUS = 'ACTIVE';

        IF @EXISTING_CART_ITEM_ID IS NOT NULL
        BEGIN
            UPDATE dbo.CART_ITEMS
            SET QUANTITY = QUANTITY + @QUANTITY,
                SPECIAL_INSTRUCTIONS = ISNULL(@SPECIAL_INSTRUCTIONS, SPECIAL_INSTRUCTIONS),
                UPDATED_AT = SYSUTCDATETIME()
            WHERE CART_ITEM_ID = @EXISTING_CART_ITEM_ID;
        END
        ELSE
        BEGIN
            INSERT INTO dbo.CART_ITEMS (CART_ID, DOC_NO, PRODUCT_ID, QUANTITY, SPECIAL_INSTRUCTIONS, ITEM_STATUS, ITEM_SIGNATURE, CREATED_AT)
            VALUES (@CART_ID, @CART_DOC_NO, @PRODUCT_ID, @QUANTITY, @SPECIAL_INSTRUCTIONS, 'ACTIVE', @ITEM_SIGNATURE, SYSUTCDATETIME());

            SET @EXISTING_CART_ITEM_ID = SCOPE_IDENTITY();

            INSERT INTO dbo.CART_ITEM_CUSTOMIZATIONS (CART_ITEM_ID, DOC_NO, CUSTOMIZATION_OPTION_ID, CREATED_AT)
            SELECT DISTINCT @EXISTING_CART_ITEM_ID, @CART_DOC_NO, OPTION_ID, SYSUTCDATETIME()
            FROM @OPTION_IDS;
        END;

        -- Update Cart timestamp
        UPDATE dbo.CARTS
        SET UPDATED_AT = SYSUTCDATETIME()
        WHERE CART_ID = @CART_ID;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        DECLARE @ERRMSG NVARCHAR(4000) = ERROR_MESSAGE();
        RAISERROR(@ERRMSG, 16, 1);
        RETURN;
    END CATCH;
END;
GO
