IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PR_GET_PRODUCT_CUSTOMIZATION_HIERARCHY]') AND type in (N'P', N'PC'))
    DROP PROCEDURE [dbo].[PR_GET_PRODUCT_CUSTOMIZATION_HIERARCHY];
GO

CREATE PROCEDURE [dbo].[PR_GET_PRODUCT_CUSTOMIZATION_HIERARCHY]
    @PRODUCT_ID BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    -- 1. Product Info
    SELECT 
        p.PRODUCT_ID AS ProductId,
        p.PRODUCT_NAME_EN AS ProductNameEn,
        p.PRODUCT_NAME_AR AS ProductNameAr,
        p.IS_CUSTOMIZABLE AS IsCustomizable,
        p.CUSTOMIZATION_TEMPLATE_ID AS CustomizationTemplateId
    FROM dbo.PRODUCTS p
    WHERE p.PRODUCT_ID = @PRODUCT_ID AND (p.IS_DELETED = 0 OR p.IS_DELETED IS NULL);

    -- 2. Template Info
    SELECT TOP 1
        t.CUSTOMIZATION_TEMPLATE_ID AS CustomizationTemplateId,
        t.DOC_NO AS DocNo,
        t.TEMPLATE_NAME_EN AS TemplateNameEn,
        t.TEMPLATE_NAME_AR AS TemplateNameAr,
        t.DESCRIPTION_EN AS DescriptionEn,
        t.DESCRIPTION_AR AS DescriptionAr,
        t.IS_ACTIVE AS IsActive
    FROM dbo.CUSTOMIZATION_TEMPLATES t
    INNER JOIN dbo.PRODUCTS p ON p.CUSTOMIZATION_TEMPLATE_ID = t.CUSTOMIZATION_TEMPLATE_ID
    WHERE p.PRODUCT_ID = @PRODUCT_ID AND t.IS_ACTIVE = 1;

    -- 3. Groups (Only mapped groups for this product's template)
    SELECT DISTINCT
        g.CUSTOMIZATION_GROUP_ID AS CustomizationGroupId,
        g.GROUP_CODE AS GroupCode,
        g.GROUP_NAME_EN AS GroupNameEn,
        g.GROUP_NAME_AR AS GroupNameAr,
        g.IS_ADDITIONAL_PRICE_AVAILABLE AS IsAdditionalPriceAvailable,
        g.PRICING_TYPE AS PricingType,
        g.PRICING_VALUE AS PricingValue,
        g.IS_CUSTOM_DATA_ALLOWED AS IsCustomDataAllowed,
        g.IS_ACTIVE AS IsActive
    FROM dbo.CUSTOMIZATION_GROUPS g
    INNER JOIN dbo.TEMPLATE_GROUP_MAPPING m ON m.CUSTOMIZATION_GROUP_ID = g.CUSTOMIZATION_GROUP_ID
    INNER JOIN dbo.PRODUCTS p ON p.CUSTOMIZATION_TEMPLATE_ID = m.CUSTOMIZATION_TEMPLATE_ID
    WHERE p.PRODUCT_ID = @PRODUCT_ID AND g.IS_ACTIVE = 1 AND m.IS_ACTIVE = 1;

    -- 4. Options for mapped groups
    SELECT 
        o.CUSTOMIZATION_OPTION_ID AS CustomizationOptionId,
        o.CUSTOMIZATION_GROUP_ID AS CustomizationGroupId,
        o.OPTION_CODE AS OptionCode,
        o.OPTION_NAME_EN AS OptionNameEn,
        o.OPTION_NAME_AR AS OptionNameAr,
        o.ADDITIONAL_PRICE AS AdditionalPrice,
        o.IS_ACTIVE AS IsActive
    FROM dbo.CUSTOMIZATION_OPTIONS o
    INNER JOIN dbo.TEMPLATE_GROUP_MAPPING m ON m.CUSTOMIZATION_GROUP_ID = o.CUSTOMIZATION_GROUP_ID
    INNER JOIN dbo.PRODUCTS p ON p.CUSTOMIZATION_TEMPLATE_ID = m.CUSTOMIZATION_TEMPLATE_ID
    WHERE p.PRODUCT_ID = @PRODUCT_ID AND o.IS_ACTIVE = 1 AND m.IS_ACTIVE = 1;
END;
GO
