-- =============================================================================
-- STORED PROCEDURE: dbo.PR_SET_DEFAULT_CUSTOMER_ADDRESS
-- =============================================================================

CREATE OR ALTER PROCEDURE dbo.PR_SET_DEFAULT_CUSTOMER_ADDRESS
    @ADDRESS_ID BIGINT,
    @CUSTOMER_USER_ID BIGINT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRANSACTION;

    UPDATE dbo.CUSTOMER_ADDRESSES
    SET IS_DEFAULT = 0, UPDATED_AT = SYSUTCDATETIME()
    WHERE CUSTOMER_USER_ID = @CUSTOMER_USER_ID;

    UPDATE dbo.CUSTOMER_ADDRESSES
    SET IS_DEFAULT = 1, UPDATED_AT = SYSUTCDATETIME()
    WHERE ADDRESS_ID = @ADDRESS_ID 
      AND CUSTOMER_USER_ID = @CUSTOMER_USER_ID;

    COMMIT TRANSACTION;
END;
GO
