-- =============================================================================
-- STORED PROCEDURE: dbo.PR_SAVE_COUPON
-- Description: Unified CUD procedure for coupons (ADD, EDIT, DELETE modes).
-- =============================================================================

CREATE OR ALTER PROCEDURE dbo.PR_SAVE_COUPON
    @MODE                 VARCHAR(10),
    @COUPON_ID            BIGINT = NULL,
    @COUPON_CODE          VARCHAR(50) = NULL,
    @DISCOUNT_TYPE        VARCHAR(20) = NULL,
    @DISCOUNT_VALUE       DECIMAL(18,2) = NULL,
    @MAX_DISCOUNT_AMOUNT  DECIMAL(18,2) = NULL,
    @MINIMUM_ORDER_AMOUNT DECIMAL(18,2) = NULL,
    @VALID_FROM           DATETIME2 = NULL,
    @VALID_TO             DATETIME2 = NULL,
    @USAGE_LIMIT_TOTAL    INT = NULL,
    @USAGE_LIMIT_PER_USER INT = NULL,
    @COUPON_STATUS        VARCHAR(20) = NULL,
    @COUPON_DESC          NVARCHAR(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;


    IF @MODE = 'ADD'
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.COUPONS WHERE COUPON_CODE = @COUPON_CODE)
        BEGIN
            RAISERROR('Coupon code already exists.', 16, 1);
            RETURN;
        END;

        INSERT INTO dbo.COUPONS(COUPON_CODE,DISCOUNT_TYPE,DISCOUNT_VALUE,MAX_DISCOUNT_AMOUNT,MINIMUM_ORDER_AMOUNT,VALID_FROM,VALID_TO,USAGE_LIMIT_TOTAL,USAGE_LIMIT_PER_USER,COUPON_STATUS,COUPON_DESC,CREATED_AT)
        VALUES(@COUPON_CODE,@DISCOUNT_TYPE,@DISCOUNT_VALUE,@MAX_DISCOUNT_AMOUNT,ISNULL(@MINIMUM_ORDER_AMOUNT, 0.00),@VALID_FROM,@VALID_TO,@USAGE_LIMIT_TOTAL,@USAGE_LIMIT_PER_USER,ISNULL(@COUPON_STATUS, 'ACTIVE'),@COUPON_DESC,SYSUTCDATETIME());

        SET @COUPON_ID = CAST(SCOPE_IDENTITY() AS BIGINT);

        SELECT COUPON_ID AS CouponId,COUPON_CODE AS CouponCode,DISCOUNT_TYPE AS DiscountType,DISCOUNT_VALUE AS DiscountValue,MAX_DISCOUNT_AMOUNT AS MaxDiscountAmount,MINIMUM_ORDER_AMOUNT AS MinimumOrderAmount,VALID_FROM AS ValidFrom,VALID_TO AS ValidTo,USAGE_LIMIT_TOTAL AS UsageLimitTotal,USAGE_LIMIT_PER_USER AS UsageLimitPerUser,COUPON_STATUS AS CouponStatus,COUPON_DESC AS CouponDesc,CREATED_AT AS CreatedAt,UPDATED_AT AS UpdatedAt
         FROM dbo.COUPONS WHERE COUPON_ID = @COUPON_ID;

        RETURN;
    END;


    IF @MODE = 'EDIT'
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.COUPONS WHERE COUPON_CODE = @COUPON_CODE AND COUPON_ID <> @COUPON_ID)
        BEGIN
            RAISERROR('Coupon code already exists.', 16, 1);
            RETURN;
        END;

        UPDATE dbo.COUPONS SET COUPON_CODE = ISNULL(@COUPON_CODE, COUPON_CODE),DISCOUNT_TYPE = ISNULL(@DISCOUNT_TYPE, DISCOUNT_TYPE),DISCOUNT_VALUE = ISNULL(@DISCOUNT_VALUE, DISCOUNT_VALUE),
        MAX_DISCOUNT_AMOUNT = @MAX_DISCOUNT_AMOUNT,MINIMUM_ORDER_AMOUNT = ISNULL(@MINIMUM_ORDER_AMOUNT, MINIMUM_ORDER_AMOUNT),VALID_FROM = ISNULL(@VALID_FROM, VALID_FROM),
        VALID_TO = ISNULL(@VALID_TO, VALID_TO),USAGE_LIMIT_TOTAL = @USAGE_LIMIT_TOTAL,USAGE_LIMIT_PER_USER = @USAGE_LIMIT_PER_USER,COUPON_STATUS = ISNULL(@COUPON_STATUS, COUPON_STATUS),COUPON_DESC = ISNULL(@COUPON_DESC, COUPON_DESC),UPDATED_AT = SYSUTCDATETIME()
        WHERE COUPON_ID = @COUPON_ID;

        SELECT COUPON_ID AS CouponId,COUPON_CODE AS CouponCode,DISCOUNT_TYPE AS DiscountType,DISCOUNT_VALUE AS DiscountValue,MAX_DISCOUNT_AMOUNT AS MaxDiscountAmount,MINIMUM_ORDER_AMOUNT AS MinimumOrderAmount,
        VALID_FROM AS ValidFrom,VALID_TO AS ValidTo,USAGE_LIMIT_TOTAL AS UsageLimitTotal,USAGE_LIMIT_PER_USER AS UsageLimitPerUser,COUPON_STATUS AS CouponStatus,COUPON_DESC AS CouponDesc,CREATED_AT AS CreatedAt,UPDATED_AT AS UpdatedAt
        FROM dbo.COUPONS WHERE COUPON_ID = @COUPON_ID;

        RETURN;
    END;

    IF @MODE = 'DELETE'
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.COUPON_USAGES WHERE COUPON_ID = @COUPON_ID)
        BEGIN
            RAISERROR('Cannot delete coupon because historical usage records exist.', 16, 1);
            RETURN;
        END;

        DELETE FROM dbo.COUPONS
        WHERE COUPON_ID = @COUPON_ID;

        SELECT @COUPON_ID AS CouponId;

        RETURN;
    END;
END;
GO
