-- =============================================================================
-- STORED PROCEDURE: dbo.PR_SAVE_PRODUCT_WEIGHT_OPTION
-- Description: Creates/Updates a weight option and its associated price for a product.
-- =============================================================================

CREATE OR ALTER PROCEDURE dbo.PR_SAVE_PRODUCT_WEIGHT_OPTION
    @PRODUCT_ID                 BIGINT,
    @UNIT_ID                    INT,
    @UNIT_VALUE                 DECIMAL(10,3) = NULL,
    @IS_CUSTOM_WEIGHT           BIT = 0,
    @MIN_WEIGHT                 DECIMAL(10,3) = NULL,
    @MAX_WEIGHT                 DECIMAL(10,3) = NULL,
    @MIN_ORDER_QUANTITY         DECIMAL(18,3) = 1.0,
    @MAX_ORDER_QUANTITY         DECIMAL(18,3) = NULL,
    @QUANTITY_INCREMENT         DECIMAL(18,3) = 1.0,
    @IS_DEFAULT                 BIT = 0,
    @DISPLAY_ORDER              INT = 0,
    @IS_ACTIVE                  BIT = 1,
    @PRICE_TYPE                 VARCHAR(20) = 'FIXED',
    @REGULAR_PRICE              DECIMAL(18,2),
    @DISCOUNT_PRICE             DECIMAL(18,2) = NULL,
    @CURRENCY_CODE              VARCHAR(10) = 'AED'
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @WEIGHT_OPTION_ID BIGINT;

    INSERT INTO dbo.PRODUCT_WEIGHT_OPTIONS
    (
        PRODUCT_ID, UNIT_ID, UNIT_VALUE, IS_CUSTOM_WEIGHT, MIN_WEIGHT, MAX_WEIGHT,
        MIN_ORDER_QUANTITY, MAX_ORDER_QUANTITY, QUANTITY_INCREMENT, IS_DEFAULT, DISPLAY_ORDER, IS_ACTIVE, CREATED_AT
    )
    VALUES
    (
        @PRODUCT_ID, @UNIT_ID, @UNIT_VALUE, ISNULL(@IS_CUSTOM_WEIGHT, 0), @MIN_WEIGHT, @MAX_WEIGHT,
        ISNULL(@MIN_ORDER_QUANTITY, 1.0), @MAX_ORDER_QUANTITY, ISNULL(@QUANTITY_INCREMENT, 1.0),
        ISNULL(@IS_DEFAULT, 0), ISNULL(@DISPLAY_ORDER, 0), ISNULL(@IS_ACTIVE, 1), SYSUTCDATETIME()
    );

    SET @WEIGHT_OPTION_ID = SCOPE_IDENTITY();

    INSERT INTO dbo.PRODUCT_PRICES
    (
        PRODUCT_ID, PRODUCT_WEIGHT_OPTION_ID, PRICE_TYPE, REGULAR_PRICE, DISCOUNT_PRICE, CURRENCY_CODE, IS_ACTIVE, CREATED_AT
    )
    VALUES
    (
        @PRODUCT_ID, @WEIGHT_OPTION_ID, ISNULL(@PRICE_TYPE, 'FIXED'), @REGULAR_PRICE, @DISCOUNT_PRICE, ISNULL(@CURRENCY_CODE, 'AED'), ISNULL(@IS_ACTIVE, 1), SYSUTCDATETIME()
    );

    SELECT @WEIGHT_OPTION_ID AS ProductWeightOptionId;
END;
GO
