CREATE OR ALTER PROCEDURE dbo.PR_UPDATE_CART_ITEM_CUSTOMIZATION
    @CUSTOMER_USER_ID BIGINT,
    @CART_ITEM_ID BIGINT,
    @SPECIAL_INSTRUCTIONS NVARCHAR(500) = NULL,
    @CUSTOMIZATION_OPTION_IDS dbo.TT_CUSTOMIZATION_OPTION_IDS READONLY
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRANSACTION;

    BEGIN TRY
        -- 1. Validate Customer
        IF @CUSTOMER_USER_ID IS NULL OR @CUSTOMER_USER_ID <= 0
        BEGIN
            RAISERROR('Valid CustomerUserId is required.', 16, 1);
            RETURN;
        END;

        -- 2. Validate Cart Item exists & belongs to active customer cart
        DECLARE @CART_ID BIGINT;
        DECLARE @PRODUCT_ID BIGINT;
        DECLARE @CART_DOC_NO VARCHAR(50);

        SELECT 
            @CART_ID = ci.CART_ID,
            @PRODUCT_ID = ci.PRODUCT_ID,
            @CART_DOC_NO = ci.DOC_NO
        FROM dbo.CART_ITEMS ci
        INNER JOIN dbo.CARTS c ON ci.CART_ID = c.CART_ID
        WHERE ci.CART_ITEM_ID = @CART_ITEM_ID
          AND c.CUSTOMER_USER_ID = @CUSTOMER_USER_ID
          AND c.CART_STATUS = 'ACTIVE';

        IF @CART_ID IS NULL
        BEGIN
            RAISERROR('Cart item not found or does not belong to active customer cart.', 16, 1);
            RETURN;
        END;

        -- 3. Replace Customization Option Mappings
        DELETE FROM dbo.CART_ITEM_CUSTOMIZATIONS
        WHERE CART_ITEM_ID = @CART_ITEM_ID;

        INSERT INTO dbo.CART_ITEM_CUSTOMIZATIONS (CART_ITEM_ID, DOC_NO, CUSTOMIZATION_OPTION_ID, CREATED_AT)
        SELECT @CART_ITEM_ID, @CART_DOC_NO, OPTION_ID, SYSUTCDATETIME()
        FROM @CUSTOMIZATION_OPTION_IDS
        WHERE OPTION_ID IS NOT NULL AND OPTION_ID > 0;

        -- 4. Calculate Option String & Item Signature
        DECLARE @OPTION_STRING VARCHAR(80) = NULL;
        DECLARE @NEW_ITEM_SIGNATURE VARCHAR(100) = NULL;

        SELECT @OPTION_STRING = STRING_AGG(CAST(OPTION_ID AS VARCHAR(20)), '_') WITHIN GROUP (ORDER BY OPTION_ID)
        FROM (SELECT DISTINCT OPTION_ID FROM @CUSTOMIZATION_OPTION_IDS) AS T;

        IF @OPTION_STRING IS NULL OR @OPTION_STRING = ''
            SET @NEW_ITEM_SIGNATURE = CAST(@PRODUCT_ID AS VARCHAR(20)) + '|NONE';
        ELSE
            SET @NEW_ITEM_SIGNATURE = CAST(@PRODUCT_ID AS VARCHAR(20)) + '|' + @OPTION_STRING;

        -- 5. Update Cart Item
        UPDATE dbo.CART_ITEMS
        SET 
            ITEM_SIGNATURE = @NEW_ITEM_SIGNATURE,
            SPECIAL_INSTRUCTIONS = ISNULL(@SPECIAL_INSTRUCTIONS, SPECIAL_INSTRUCTIONS),
            UPDATED_AT = SYSUTCDATETIME()
        WHERE CART_ITEM_ID = @CART_ITEM_ID;

        -- 6. Update Cart Timestamp
        UPDATE dbo.CARTS
        SET UPDATED_AT = SYSUTCDATETIME()
        WHERE CART_ID = @CART_ID;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        THROW;
    END CATCH;
END;
GO
