CREATE OR ALTER PROCEDURE dbo.PR_UPDATE_CART_ITEM_CUSTOMIZATION
    @CUSTOMER_USER_ID BIGINT,
    @CART_ITEM_ID BIGINT,
    @SPECIAL_INSTRUCTIONS NVARCHAR(500) = NULL,
    @CUSTOMIZATION_OPTION_IDS dbo.TT_CUSTOMIZATION_OPTION_IDS READONLY
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRANSACTION;

    BEGIN TRY
        -- 1. Validate Customer
        IF @CUSTOMER_USER_ID IS NULL OR @CUSTOMER_USER_ID <= 0
        BEGIN
            RAISERROR('Valid CustomerUserId is required.', 16, 1);
            RETURN;
        END;

        -- 2. Validate Cart Item exists & belongs to active customer cart
        DECLARE @CART_ID BIGINT;
        DECLARE @PRODUCT_ID BIGINT;
        DECLARE @QUANTITY INT;
        DECLARE @BASE_PRICE DECIMAL(18, 2);

        SELECT 
            @CART_ID = ci.CART_ID,
            @PRODUCT_ID = ci.PRODUCT_ID,
            @QUANTITY = ci.QUANTITY,
            @BASE_PRICE = ci.BASE_PRICE
        FROM dbo.CART_ITEMS ci
        INNER JOIN dbo.CARTS c ON ci.CART_ID = c.CART_ID
        WHERE ci.CART_ITEM_ID = @CART_ITEM_ID
          AND c.CUSTOMER_USER_ID = @CUSTOMER_USER_ID
          AND c.IS_ACTIVE = 1;

        IF @CART_ID IS NULL
        BEGIN
            RAISERROR('Cart item not found or does not belong to active customer cart.', 16, 1);
            RETURN;
        END;

        -- 3. Replace Customization Option Mappings
        DELETE FROM dbo.CART_ITEM_CUSTOMIZATIONS
        WHERE CART_ITEM_ID = @CART_ITEM_ID;

        INSERT INTO dbo.CART_ITEM_CUSTOMIZATIONS (CART_ITEM_ID, CUSTOMIZATION_OPTION_ID)
        SELECT @CART_ITEM_ID, OPTION_ID
        FROM @CUSTOMIZATION_OPTION_IDS
        WHERE OPTION_ID IS NOT NULL AND OPTION_ID > 0;

        -- 4. Calculate Option String & Extra Price
        DECLARE @OPTION_STRING NVARCHAR(MAX) = '';
        DECLARE @CUSTOMIZATION_EXTRA_PRICE DECIMAL(18, 2) = 0.00;

        SELECT 
            @OPTION_STRING = STRING_AGG(CAST(co.CUSTOMIZATION_OPTION_ID AS NVARCHAR(20)), '_') WITHIN GROUP (ORDER BY co.CUSTOMIZATION_OPTION_ID ASC),
            @CUSTOMIZATION_EXTRA_PRICE = ISNULL(SUM(co.ADDITIONAL_PRICE), 0.00)
        FROM @CUSTOMIZATION_OPTION_IDS t
        INNER JOIN dbo.CUSTOMIZATION_OPTIONS co ON t.OPTION_ID = co.CUSTOMIZATION_OPTION_ID;

        IF @OPTION_STRING IS NULL OR @OPTION_STRING = ''
        BEGIN
            SET @OPTION_STRING = 'NONE';
        END;

        DECLARE @NEW_ITEM_SIGNATURE NVARCHAR(200) = CAST(@PRODUCT_ID AS NVARCHAR(20)) + '|' + @OPTION_STRING;

        -- 5. Calculate New Prices
        DECLARE @NEW_UNIT_PRICE DECIMAL(18, 2) = @BASE_PRICE + @CUSTOMIZATION_EXTRA_PRICE;
        DECLARE @NEW_TOTAL_PRICE DECIMAL(18, 2) = @NEW_UNIT_PRICE * @QUANTITY;

        -- 6. Update Cart Item
        UPDATE dbo.CART_ITEMS
        SET 
            ITEM_SIGNATURE = @NEW_ITEM_SIGNATURE,
            SPECIAL_INSTRUCTIONS = @SPECIAL_INSTRUCTIONS,
            CUSTOMIZATION_EXTRA_PRICE = @CUSTOMIZATION_EXTRA_PRICE,
            UNIT_PRICE = @NEW_UNIT_PRICE,
            TOTAL_PRICE = @NEW_TOTAL_PRICE,
            UPDATED_AT = GETUTCDATE()
        WHERE CART_ITEM_ID = @CART_ITEM_ID;

        -- 7. Recalculate Cart Totals
        DECLARE @NEW_SUBTOTAL DECIMAL(18, 2);

        SELECT @NEW_SUBTOTAL = ISNULL(SUM(TOTAL_PRICE), 0.00)
        FROM dbo.CART_ITEMS
        WHERE CART_ID = @CART_ID;

        UPDATE dbo.CARTS
        SET 
            SUBTOTAL_AMOUNT = @NEW_SUBTOTAL,
            NET_AMOUNT = @NEW_SUBTOTAL - DISCOUNT_AMOUNT,
            TOTAL_ITEMS = (SELECT ISNULL(SUM(QUANTITY), 0) FROM dbo.CART_ITEMS WHERE CART_ID = @CART_ID),
            UPDATED_AT = GETUTCDATE()
        WHERE CART_ID = @CART_ID;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        THROW;
    END CATCH;
END;
GO
