-- =============================================================================
-- Migration: 0029_Create_Product_Catalog_Tables.sql
-- Description: Creates dbo.PRODUCTS, dbo.PRODUCT_WEIGHT_OPTIONS,
--              dbo.PRODUCT_PRICES, and dbo.PRODUCT_IMAGES tables.
-- =============================================================================

-- 1. PRODUCTS TABLE
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('dbo.PRODUCTS'))
BEGIN
    CREATE TABLE dbo.PRODUCTS
    (
        PRODUCT_ID                  BIGINT IDENTITY(1,1) NOT NULL,
        CATEGORY_ID                 BIGINT NOT NULL,
        PRODUCT_CODE                VARCHAR(50) NOT NULL,
        PRODUCT_NAME_EN             NVARCHAR(200) NOT NULL,
        PRODUCT_NAME_AR             NVARCHAR(200) NOT NULL,
        DESCRIPTION_EN              NVARCHAR(2000) NULL,
        DESCRIPTION_AR              NVARCHAR(2000) NULL,
        FRESHNESS_TYPE              VARCHAR(20) NOT NULL DEFAULT 'FRESH',
        COUNTRY_OF_ORIGIN           NVARCHAR(100) NULL,
        IS_HALAL_CERTIFIED          BIT NOT NULL DEFAULT 1,
        HALAL_CERTIFICATE_NO        VARCHAR(100) NULL,
        HALAL_CERTIFICATE_URL       VARCHAR(500) NULL,
        NUTRITION_INFORMATION_EN    NVARCHAR(2000) NULL,
        NUTRITION_INFORMATION_AR    NVARCHAR(2000) NULL,
        STORAGE_INSTRUCTIONS_EN     NVARCHAR(1000) NULL,
        STORAGE_INSTRUCTIONS_AR     NVARCHAR(1000) NULL,
        IS_CUSTOMIZABLE             BIT NOT NULL DEFAULT 0,
        CUSTOMIZATION_TEMPLATE_ID   BIGINT NULL,
        DISPLAY_ORDER               INT NOT NULL DEFAULT 0,
        IS_FEATURED                 BIT NOT NULL DEFAULT 0,
        IS_BESTSELLER               BIT NOT NULL DEFAULT 0,
        IS_ACTIVE                   BIT NOT NULL DEFAULT 1,
        CREATED_AT                  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT                  DATETIME2 NULL,

        CONSTRAINT PK_PRODUCTS PRIMARY KEY CLUSTERED (PRODUCT_ID),
        CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (CATEGORY_ID) 
            REFERENCES dbo.CATEGORIES (CATEGORY_ID),
        CONSTRAINT UQ_PRODUCTS_CODE UNIQUE NONCLUSTERED (PRODUCT_CODE)
    );

    CREATE NONCLUSTERED INDEX IX_PRODUCTS_CATEGORY 
        ON dbo.PRODUCTS (CATEGORY_ID, IS_ACTIVE);

    CREATE NONCLUSTERED INDEX IX_PRODUCTS_FEATURED 
        ON dbo.PRODUCTS (IS_FEATURED, IS_ACTIVE) 
        WHERE IS_FEATURED = 1;

    CREATE NONCLUSTERED INDEX IX_PRODUCTS_BESTSELLER 
        ON dbo.PRODUCTS (IS_BESTSELLER, IS_ACTIVE) 
        WHERE IS_BESTSELLER = 1;
END;
GO

-- 2. PRODUCT_WEIGHT_OPTIONS TABLE
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('dbo.PRODUCT_WEIGHT_OPTIONS'))
BEGIN
    CREATE TABLE dbo.PRODUCT_WEIGHT_OPTIONS
    (
        PRODUCT_WEIGHT_OPTION_ID    BIGINT IDENTITY(1,1) NOT NULL,
        PRODUCT_ID                  BIGINT NOT NULL,
        UNIT_ID                     INT NOT NULL,
        UNIT_VALUE                  DECIMAL(10,3) NULL,
        IS_CUSTOM_WEIGHT            BIT NOT NULL DEFAULT 0,
        MIN_WEIGHT                  DECIMAL(10,3) NULL,
        MAX_WEIGHT                  DECIMAL(10,3) NULL,
        MIN_ORDER_QUANTITY          DECIMAL(18,3) NOT NULL DEFAULT 1.0,
        MAX_ORDER_QUANTITY          DECIMAL(18,3) NULL,
        QUANTITY_INCREMENT          DECIMAL(18,3) NOT NULL DEFAULT 1.0,
        IS_DEFAULT                  BIT NOT NULL DEFAULT 0,
        DISPLAY_ORDER               INT NOT NULL DEFAULT 0,
        IS_ACTIVE                   BIT NOT NULL DEFAULT 1,
        CREATED_AT                  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT                  DATETIME2 NULL,

        CONSTRAINT PK_PRODUCT_WEIGHT_OPTIONS PRIMARY KEY CLUSTERED (PRODUCT_WEIGHT_OPTION_ID),
        CONSTRAINT FK_PRODUCT_WEIGHT_OPTIONS_PRODUCT FOREIGN KEY (PRODUCT_ID) 
            REFERENCES dbo.PRODUCTS (PRODUCT_ID) ON DELETE CASCADE,
        CONSTRAINT FK_PRODUCT_WEIGHT_OPTIONS_UNIT FOREIGN KEY (UNIT_ID) 
            REFERENCES dbo.MEASUREMENT_UNITS (UNIT_ID)
    );

    CREATE NONCLUSTERED INDEX IX_PRODUCT_WEIGHT_OPTIONS_PRODUCT 
        ON dbo.PRODUCT_WEIGHT_OPTIONS (PRODUCT_ID, IS_ACTIVE);
END;
GO

-- 3. PRODUCT_PRICES TABLE
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('dbo.PRODUCT_PRICES'))
BEGIN
    CREATE TABLE dbo.PRODUCT_PRICES
    (
        PRODUCT_PRICE_ID            BIGINT IDENTITY(1,1) NOT NULL,
        PRODUCT_ID                  BIGINT NOT NULL,
        PRODUCT_WEIGHT_OPTION_ID    BIGINT NOT NULL,
        PRICE_TYPE                  VARCHAR(20) NOT NULL DEFAULT 'FIXED',
        REGULAR_PRICE               DECIMAL(18,2) NOT NULL,
        DISCOUNT_PRICE              DECIMAL(18,2) NULL,
        CURRENCY_CODE               VARCHAR(10) NOT NULL DEFAULT 'AED',
        IS_ACTIVE                   BIT NOT NULL DEFAULT 1,
        CREATED_AT                  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT                  DATETIME2 NULL,

        CONSTRAINT PK_PRODUCT_PRICES PRIMARY KEY CLUSTERED (PRODUCT_PRICE_ID),
        CONSTRAINT FK_PRODUCT_PRICES_PRODUCT FOREIGN KEY (PRODUCT_ID) 
            REFERENCES dbo.PRODUCTS (PRODUCT_ID) ON DELETE CASCADE,
        CONSTRAINT FK_PRODUCT_PRICES_WEIGHT_OPTION FOREIGN KEY (PRODUCT_WEIGHT_OPTION_ID) 
            REFERENCES dbo.PRODUCT_WEIGHT_OPTIONS (PRODUCT_WEIGHT_OPTION_ID)
    );

    CREATE NONCLUSTERED INDEX IX_PRODUCT_PRICES_WEIGHT_OPTION 
        ON dbo.PRODUCT_PRICES (PRODUCT_WEIGHT_OPTION_ID, IS_ACTIVE);
END;
GO

-- 4. PRODUCT_IMAGES TABLE
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('dbo.PRODUCT_IMAGES'))
BEGIN
    CREATE TABLE dbo.PRODUCT_IMAGES
    (
        PRODUCT_IMAGE_ID    BIGINT IDENTITY(1,1) NOT NULL,
        PRODUCT_ID          BIGINT NOT NULL,
        IMAGE_URL           VARCHAR(500) NOT NULL,
        IS_PRIMARY          BIT NOT NULL DEFAULT 0,
        DISPLAY_ORDER       INT NOT NULL DEFAULT 0,
        IS_ACTIVE           BIT NOT NULL DEFAULT 1,
        CREATED_AT          DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT          DATETIME2 NULL,

        CONSTRAINT PK_PRODUCT_IMAGES PRIMARY KEY CLUSTERED (PRODUCT_IMAGE_ID),
        CONSTRAINT FK_PRODUCT_IMAGES_PRODUCT FOREIGN KEY (PRODUCT_ID) 
            REFERENCES dbo.PRODUCTS (PRODUCT_ID) ON DELETE CASCADE
    );

    CREATE NONCLUSTERED INDEX IX_PRODUCT_IMAGES_PRODUCT 
        ON dbo.PRODUCT_IMAGES (PRODUCT_ID, IS_ACTIVE, DISPLAY_ORDER);
END;
GO
