-- Migration: 0043_Refactor_Product_Catalogue_Tables.sql
-- Description: Refactors Product Catalogue tables to match exact Notion specs.
--              - Drops PRODUCT_WEIGHT_OPTIONS table.
--              - Adds UNIT_ID, DISCOUNT_PERCENTAGE, and STOCK_COUNT to PRODUCTS table.
--              - Safely drops dependent indexes, default constraints, and obsolete columns from PRODUCTS.
--              - Restructures PRODUCT_PRICES to reference PRODUCT_ID directly.
--              - Restructures PRODUCT_IMAGES to 1:1 per product with PRIMARY_URL, SECONDARY_URL, TERTIARY_URL.

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_PRODUCT_PRICES_WEIGHT_OPTION')
    ALTER TABLE dbo.PRODUCT_PRICES DROP CONSTRAINT FK_PRODUCT_PRICES_WEIGHT_OPTION;
GO

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'PRODUCT_WEIGHT_OPTIONS')
    DROP TABLE dbo.PRODUCT_WEIGHT_OPTIONS;
GO

-- Drop dependent indexes before dropping columns
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PRODUCTS_BESTSELLER' AND object_id = OBJECT_ID('dbo.PRODUCTS'))
    DROP INDEX IX_PRODUCTS_BESTSELLER ON dbo.PRODUCTS;
GO

-- 1. Update PRODUCTS table
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'UNIT_ID')
BEGIN
    ALTER TABLE dbo.PRODUCTS ADD UNIT_ID INT NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'DISCOUNT_PERCENTAGE')
BEGIN
    ALTER TABLE dbo.PRODUCTS ADD DISCOUNT_PERCENTAGE DECIMAL(5,2) NOT NULL DEFAULT 0;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'STOCK_COUNT')
BEGIN
    ALTER TABLE dbo.PRODUCTS ADD STOCK_COUNT DECIMAL(18,3) NOT NULL DEFAULT 0;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'IS_DELETED')
BEGIN
    ALTER TABLE dbo.PRODUCTS ADD IS_DELETED BIT NOT NULL DEFAULT 0;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'DELETED_AT')
BEGIN
    ALTER TABLE dbo.PRODUCTS ADD DELETED_AT DATETIME2 NULL;
END
GO

-- Helper block: Drop default constraints on columns before dropping columns
DECLARE @sql NVARCHAR(MAX) = N'';

SELECT @sql += N'ALTER TABLE dbo.PRODUCTS DROP CONSTRAINT ' + QUOTENAME(dc.name) + N';' + CHAR(13)
FROM sys.default_constraints dc
JOIN sys.columns c ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id
WHERE dc.parent_object_id = OBJECT_ID('dbo.PRODUCTS')
  AND c.name IN (
    'COUNTRY_OF_ORIGIN',
    'IS_HALAL_CERTIFIED',
    'HALAL_CERTIFICATE_NO',
    'HALAL_CERTIFICATE_URL',
    'NUTRITION_INFORMATION_EN',
    'NUTRITION_INFORMATION_AR',
    'STORAGE_INSTRUCTIONS_EN',
    'STORAGE_INSTRUCTIONS_AR',
    'DISPLAY_ORDER',
    'IS_BESTSELLER'
  );

IF LEN(@sql) > 0
    EXEC sp_executesql @sql;
GO

-- Drop obsolete columns
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'COUNTRY_OF_ORIGIN')
    ALTER TABLE dbo.PRODUCTS DROP COLUMN COUNTRY_OF_ORIGIN;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'IS_HALAL_CERTIFIED')
    ALTER TABLE dbo.PRODUCTS DROP COLUMN IS_HALAL_CERTIFIED;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'HALAL_CERTIFICATE_NO')
    ALTER TABLE dbo.PRODUCTS DROP COLUMN HALAL_CERTIFICATE_NO;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'HALAL_CERTIFICATE_URL')
    ALTER TABLE dbo.PRODUCTS DROP COLUMN HALAL_CERTIFICATE_URL;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'NUTRITION_INFORMATION_EN')
    ALTER TABLE dbo.PRODUCTS DROP COLUMN NUTRITION_INFORMATION_EN;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'NUTRITION_INFORMATION_AR')
    ALTER TABLE dbo.PRODUCTS DROP COLUMN NUTRITION_INFORMATION_AR;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'STORAGE_INSTRUCTIONS_EN')
    ALTER TABLE dbo.PRODUCTS DROP COLUMN STORAGE_INSTRUCTIONS_EN;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'STORAGE_INSTRUCTIONS_AR')
    ALTER TABLE dbo.PRODUCTS DROP COLUMN STORAGE_INSTRUCTIONS_AR;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'DISPLAY_ORDER')
    ALTER TABLE dbo.PRODUCTS DROP COLUMN DISPLAY_ORDER;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'IS_BESTSELLER')
    ALTER TABLE dbo.PRODUCTS DROP COLUMN IS_BESTSELLER;
GO

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PRODUCTS') AND name = 'UNIT_ID')
BEGIN
    UPDATE dbo.PRODUCTS SET UNIT_ID = 1 WHERE UNIT_ID IS NULL;
    
    IF EXISTS (SELECT * FROM sys.tables WHERE name = 'MEASUREMENT_UNITS')
    BEGIN
        IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_PRODUCTS_UNIT')
        BEGIN
            ALTER TABLE dbo.PRODUCTS ADD CONSTRAINT FK_PRODUCTS_UNIT FOREIGN KEY (UNIT_ID) REFERENCES dbo.MEASUREMENT_UNITS(UNIT_ID);
        END
    END
END
GO

-- 2. Update PRODUCT_PRICES table
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'PRODUCT_PRICES')
BEGIN
    DROP TABLE dbo.PRODUCT_PRICES;
END
GO

CREATE TABLE dbo.PRODUCT_PRICES
(
    PRICE_ID            BIGINT IDENTITY(1,1) NOT NULL,
    PRODUCT_ID          BIGINT NOT NULL,
    PRICE               DECIMAL(18,2) NOT NULL,
    IS_ACTIVE           BIT NOT NULL DEFAULT 1,
    CREATED_AT          DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT          DATETIME2 NULL,

    CONSTRAINT PK_PRODUCT_PRICES PRIMARY KEY CLUSTERED (PRICE_ID),
    CONSTRAINT FK_PRODUCT_PRICES_PRODUCT FOREIGN KEY (PRODUCT_ID) 
        REFERENCES dbo.PRODUCTS (PRODUCT_ID) ON DELETE CASCADE
);

CREATE NONCLUSTERED INDEX IX_PRODUCT_PRICES_PRODUCT 
    ON dbo.PRODUCT_PRICES (PRODUCT_ID, IS_ACTIVE);
GO

-- 3. Update PRODUCT_IMAGES table
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'PRODUCT_IMAGES')
BEGIN
    DROP TABLE dbo.PRODUCT_IMAGES;
END
GO

CREATE TABLE dbo.PRODUCT_IMAGES
(
    IMAGE_ID            BIGINT IDENTITY(1,1) NOT NULL,
    PRODUCT_ID          BIGINT NOT NULL,
    PRIMARY_URL         VARCHAR(500) NOT NULL,
    SECONDARY_URL       VARCHAR(500) NULL,
    TERTIARY_URL        VARCHAR(500) NULL,

    CONSTRAINT PK_PRODUCT_IMAGES PRIMARY KEY CLUSTERED (IMAGE_ID),
    CONSTRAINT FK_PRODUCT_IMAGES_PRODUCT FOREIGN KEY (PRODUCT_ID) 
        REFERENCES dbo.PRODUCTS (PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PRODUCT_IMAGES_PRODUCT UNIQUE NONCLUSTERED (PRODUCT_ID)
);
GO
