-- Migration: 0046_Fix_PR_GET_PRODUCTS_Search.sql
-- Description: Updates stored procedure PR_GET_PRODUCTS to include category names and product descriptions in SEARCH_TERM matching.

IF OBJECT_ID('dbo.PR_GET_PRODUCTS', 'P') IS NOT NULL
    DROP PROCEDURE dbo.PR_GET_PRODUCTS;
GO

EXEC('
CREATE PROCEDURE dbo.PR_GET_PRODUCTS
    @PRODUCT_ID     BIGINT = NULL,
    @CATEGORY_ID    BIGINT = NULL,
    @SEARCH_TERM    NVARCHAR(200) = NULL,
    @IS_FEATURED    BIT = NULL,
    @IS_NEW_ARRIVAL BIT = NULL,
    @IS_ACTIVE      BIT = NULL,
    @IS_DELETED     BIT = NULL,
    @PAGE_NUMBER    INT = 1,
    @PAGE_SIZE      INT = 10
AS
BEGIN
    SET NOCOUNT ON;

    SET @PAGE_NUMBER = ISNULL(@PAGE_NUMBER, 1);
    IF @PAGE_NUMBER < 1 SET @PAGE_NUMBER = 1;

    SET @PAGE_SIZE = ISNULL(@PAGE_SIZE, 10);
    IF @PAGE_SIZE < 1 SET @PAGE_SIZE = 10;

    SET @SEARCH_TERM = NULLIF(LTRIM(RTRIM(@SEARCH_TERM)), '''');

    -- 1. Total Count
    SELECT COUNT(1)
    FROM dbo.PRODUCTS p
    INNER JOIN dbo.CATEGORIES c ON p.CATEGORY_ID = c.CATEGORY_ID
    WHERE (@PRODUCT_ID IS NULL OR p.PRODUCT_ID = @PRODUCT_ID)
      AND (@CATEGORY_ID IS NULL OR p.CATEGORY_ID = @CATEGORY_ID)
      AND (@IS_FEATURED IS NULL OR p.IS_FEATURED = @IS_FEATURED)
      AND (@IS_ACTIVE IS NULL OR p.IS_ACTIVE = @IS_ACTIVE)
      AND (@IS_DELETED IS NULL OR p.IS_DELETED = @IS_DELETED)
      AND (@IS_NEW_ARRIVAL IS NULL OR (@IS_NEW_ARRIVAL = 1 AND p.CREATED_AT >= DATEADD(DAY, -10, SYSUTCDATETIME())) OR (@IS_NEW_ARRIVAL = 0 AND p.CREATED_AT < DATEADD(DAY, -10, SYSUTCDATETIME())))
      AND (@SEARCH_TERM IS NULL OR p.PRODUCT_NAME_EN LIKE ''%'' + @SEARCH_TERM + ''%'' OR p.PRODUCT_NAME_AR LIKE ''%'' + @SEARCH_TERM + ''%'' OR c.CATEGORY_NAME_EN LIKE ''%'' + @SEARCH_TERM + ''%'' OR c.CATEGORY_NAME_AR LIKE ''%'' + @SEARCH_TERM + ''%'' OR p.DESCRIPTION_EN LIKE ''%'' + @SEARCH_TERM + ''%'' OR p.DESCRIPTION_AR LIKE ''%'' + @SEARCH_TERM + ''%'' OR p.DOC_NO LIKE ''%'' + @SEARCH_TERM + ''%'');

    -- 2. Items Result Set
    SELECT
        p.PRODUCT_ID AS ProductId,
        p.CATEGORY_ID AS CategoryId,
        c.CATEGORY_NAME_EN AS CategoryNameEn,
        c.CATEGORY_NAME_AR AS CategoryNameAr,
        p.DOC_NO AS DocNo,
        p.DOC_TYPE AS DocType,
        p.PRODUCT_NAME_EN AS ProductNameEn,
        p.PRODUCT_NAME_AR AS ProductNameAr,
        p.DESCRIPTION_EN AS DescriptionEn,
        p.DESCRIPTION_AR AS DescriptionAr,
        p.IS_CUSTOMIZABLE AS IsCustomizable,
        p.CUSTOMIZATION_TEMPLATE_ID AS CustomizationTemplateId,
        p.UNIT_ID AS UnitId,
        u.UNIT AS UnitCode,
        u.UNIT_DESCRIPTION AS UnitDescription,
        p.DISCOUNT_PERCENTAGE AS DiscountPercentage,
        p.STOCK_COUNT AS StockCount,
        pr.PRICE AS Price,
        CAST(pr.PRICE - (pr.PRICE * (p.DISCOUNT_PERCENTAGE / 100.0)) AS DECIMAL(18,2)) AS SellingPrice,
        img.PRIMARY_URL AS PrimaryUrl,
        img.SECONDARY_URL AS SecondaryUrl,
        img.TERTIARY_URL AS TertiaryUrl,
        p.IS_FEATURED AS IsFeatured,
        p.IS_ACTIVE AS IsActive,
        p.IS_DELETED AS IsDeleted,
        p.DELETED_AT AS DeletedAt,
        CASE WHEN p.CREATED_AT >= DATEADD(DAY, -10, SYSUTCDATETIME()) THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS IsNewArrival,
        p.CREATED_AT AS CreatedAt,
        p.UPDATED_AT AS UpdatedAt
    FROM dbo.PRODUCTS p
    INNER JOIN dbo.CATEGORIES c ON p.CATEGORY_ID = c.CATEGORY_ID
    INNER JOIN dbo.MEASUREMENT_UNITS u ON p.UNIT_ID = u.UNIT_ID
    LEFT JOIN dbo.PRODUCT_PRICES pr ON p.PRODUCT_ID = pr.PRODUCT_ID AND pr.IS_ACTIVE = 1
    LEFT JOIN dbo.PRODUCT_IMAGES img ON p.PRODUCT_ID = img.PRODUCT_ID
    WHERE (@PRODUCT_ID IS NULL OR p.PRODUCT_ID = @PRODUCT_ID)
      AND (@CATEGORY_ID IS NULL OR p.CATEGORY_ID = @CATEGORY_ID)
      AND (@IS_FEATURED IS NULL OR p.IS_FEATURED = @IS_FEATURED)
      AND (@IS_ACTIVE IS NULL OR p.IS_ACTIVE = @IS_ACTIVE)
      AND (@IS_DELETED IS NULL OR p.IS_DELETED = @IS_DELETED)
      AND (@IS_NEW_ARRIVAL IS NULL OR (@IS_NEW_ARRIVAL = 1 AND p.CREATED_AT >= DATEADD(DAY, -10, SYSUTCDATETIME())) OR (@IS_NEW_ARRIVAL = 0 AND p.CREATED_AT < DATEADD(DAY, -10, SYSUTCDATETIME())))
      AND (@SEARCH_TERM IS NULL OR p.PRODUCT_NAME_EN LIKE ''%'' + @SEARCH_TERM + ''%'' OR p.PRODUCT_NAME_AR LIKE ''%'' + @SEARCH_TERM + ''%'' OR c.CATEGORY_NAME_EN LIKE ''%'' + @SEARCH_TERM + ''%'' OR c.CATEGORY_NAME_AR LIKE ''%'' + @SEARCH_TERM + ''%'' OR p.DESCRIPTION_EN LIKE ''%'' + @SEARCH_TERM + ''%'' OR p.DESCRIPTION_AR LIKE ''%'' + @SEARCH_TERM + ''%'' OR p.DOC_NO LIKE ''%'' + @SEARCH_TERM + ''%'')
    ORDER BY p.CREATED_AT DESC
    OFFSET (@PAGE_NUMBER - 1) * @PAGE_SIZE ROWS
    FETCH NEXT @PAGE_SIZE ROWS ONLY;
END;
');
GO
