-- Migration: 0047_Create_PR_UPDATE_PRODUCT_STATUS.sql
-- Description: Creates stored procedure PR_UPDATE_PRODUCT_STATUS to toggle product IsActive status.

IF OBJECT_ID('dbo.PR_UPDATE_PRODUCT_STATUS', 'P') IS NOT NULL
    DROP PROCEDURE dbo.PR_UPDATE_PRODUCT_STATUS;
GO

EXEC('
CREATE PROCEDURE dbo.PR_UPDATE_PRODUCT_STATUS
    @PRODUCT_ID BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.PRODUCTS WHERE PRODUCT_ID = @PRODUCT_ID AND IS_DELETED = 0)
    BEGIN
        RAISERROR(''Product not found.'', 16, 1);
        RETURN;
    END

    UPDATE dbo.PRODUCTS
    SET IS_ACTIVE = CASE WHEN IS_ACTIVE = 1 THEN 0 ELSE 1 END,
        UPDATED_AT = SYSUTCDATETIME()
    WHERE PRODUCT_ID = @PRODUCT_ID AND IS_DELETED = 0;

    EXEC dbo.PR_GET_PRODUCTS @PRODUCT_ID = @PRODUCT_ID;
END;
');
GO
