-- Migration: 0048_Create_PR_UPDATE_PRODUCT_IMAGE.sql
-- Description: Creates stored procedure PR_UPDATE_PRODUCT_IMAGE to update product primary, secondary, and tertiary images.

IF OBJECT_ID('dbo.PR_UPDATE_PRODUCT_IMAGE', 'P') IS NOT NULL
    DROP PROCEDURE dbo.PR_UPDATE_PRODUCT_IMAGE;
GO

EXEC('
CREATE PROCEDURE dbo.PR_UPDATE_PRODUCT_IMAGE
    @PRODUCT_ID     BIGINT,
    @PRIMARY_URL    VARCHAR(500),
    @SECONDARY_URL  VARCHAR(500) = NULL,
    @TERTIARY_URL   VARCHAR(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.PRODUCTS WHERE PRODUCT_ID = @PRODUCT_ID AND IS_DELETED = 0)
    BEGIN
        RAISERROR(''Product not found.'', 16, 1);
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM dbo.PRODUCT_IMAGES WHERE PRODUCT_ID = @PRODUCT_ID)
    BEGIN
        UPDATE dbo.PRODUCT_IMAGES
        SET PRIMARY_URL = @PRIMARY_URL,
            SECONDARY_URL = @SECONDARY_URL,
            TERTIARY_URL = @TERTIARY_URL
        WHERE PRODUCT_ID = @PRODUCT_ID;
    END
    ELSE
    BEGIN
        INSERT INTO dbo.PRODUCT_IMAGES (PRODUCT_ID, PRIMARY_URL, SECONDARY_URL, TERTIARY_URL)
        VALUES (@PRODUCT_ID, @PRIMARY_URL, @SECONDARY_URL, @TERTIARY_URL);
    END

    EXEC dbo.PR_GET_PRODUCTS @PRODUCT_ID = @PRODUCT_ID;
END;
');
GO
