-- Migration: 0060_Create_Customization_Tables.sql
-- Description: Creates 4-table customization schema (CUSTOMIZATION_TEMPLATES, CUSTOMIZATION_GROUPS, TEMPLATE_GROUP_MAPPING, CUSTOMIZATION_OPTIONS), seeds CTP1 DOCTYPE in dbo.M_DOC_NO, and adds foreign key from PRODUCTS to CUSTOMIZATION_TEMPLATES.

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CUSTOMIZATION_TEMPLATES' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.CUSTOMIZATION_TEMPLATES
    (
        CUSTOMIZATION_TEMPLATE_ID   BIGINT IDENTITY(1,1) NOT NULL,
        DOC_NO                      VARCHAR(50) NOT NULL,
        DOC_TYPE                    VARCHAR(20) NOT NULL DEFAULT 'CTP1',
        TEMPLATE_NAME_EN            NVARCHAR(150) NOT NULL,
        TEMPLATE_NAME_AR            NVARCHAR(150) NOT NULL,
        DESCRIPTION_EN              NVARCHAR(500) NULL,
        DESCRIPTION_AR              NVARCHAR(500) NULL,
        IS_ACTIVE                   BIT NOT NULL DEFAULT 1,
        CREATED_AT                  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT                  DATETIME2 NULL,

        CONSTRAINT PK_CUSTOMIZATION_TEMPLATES PRIMARY KEY CLUSTERED (CUSTOMIZATION_TEMPLATE_ID),
        CONSTRAINT UQ_CUSTOMIZATION_TEMPLATES_DOC_NO UNIQUE NONCLUSTERED (DOC_NO)
    );

    CREATE NONCLUSTERED INDEX IX_CUSTOMIZATION_TEMPLATES_ACTIVE 
        ON dbo.CUSTOMIZATION_TEMPLATES (IS_ACTIVE);
END;
GO

-- Seed 'CTP1' document type configuration for Customization Templates in dbo.M_DOC_NO
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'M_DOC_NO' AND schema_id = SCHEMA_ID('dbo'))
   AND NOT EXISTS (SELECT 1 FROM dbo.M_DOC_NO WHERE DOCTYPE = 'CTP1')
BEGIN
    DECLARE @DefaultCompanyId BIGINT;
    SELECT TOP 1 @DefaultCompanyId = COMPANY_CONFIG_ID FROM dbo.COMPANY_CONFIG WHERE COMPANY_CODE = 'AL_AZIMA';

    INSERT INTO dbo.M_DOC_NO (
        MDOC,
        DOCTYPE,
        DESCRIPTION,
        COMPANY_CONFIG_ID,
        PREFIX,
        SUFFIX,
        DIGIT_NO,
        START_DOCNO,
        PERIODWISE_YN,
        PERIOD_TYPE,
        IS_ACTIVE
    )
    VALUES (
        'CTP',
        'CTP1',
        'Customization Template Document Number',
        @DefaultCompanyId,
        'CTP',
        NULL,
        10,
        0,
        'N',
        'NONE',
        1
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CUSTOMIZATION_GROUPS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.CUSTOMIZATION_GROUPS
    (
        CUSTOMIZATION_GROUP_ID          BIGINT IDENTITY(1,1) NOT NULL,
        GROUP_CODE                      VARCHAR(50) NOT NULL,
        GROUP_NAME_EN                   NVARCHAR(150) NOT NULL,
        GROUP_NAME_AR                   NVARCHAR(150) NOT NULL,
        IS_ADDITIONAL_PRICE_AVAILABLE   BIT NOT NULL DEFAULT 0,
        DISPLAY_ORDER                   INT NOT NULL DEFAULT 0,
        IS_ACTIVE                       BIT NOT NULL DEFAULT 1,
        CREATED_AT                      DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT                      DATETIME2 NULL,

        CONSTRAINT PK_CUSTOMIZATION_GROUPS PRIMARY KEY CLUSTERED (CUSTOMIZATION_GROUP_ID),
        CONSTRAINT UQ_CUSTOMIZATION_GROUPS_CODE UNIQUE NONCLUSTERED (GROUP_CODE)
    );

    CREATE NONCLUSTERED INDEX IX_CUSTOMIZATION_GROUPS_DISPLAY 
        ON dbo.CUSTOMIZATION_GROUPS (DISPLAY_ORDER, IS_ACTIVE);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TEMPLATE_GROUP_MAPPING' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.TEMPLATE_GROUP_MAPPING
    (
        TEMPLATE_GROUP_MAPPING_ID   BIGINT IDENTITY(1,1) NOT NULL,
        CUSTOMIZATION_TEMPLATE_ID   BIGINT NOT NULL,
        CUSTOMIZATION_GROUP_ID      BIGINT NOT NULL,
        IS_ACTIVE                   BIT NOT NULL DEFAULT 1,
        CREATED_AT                  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT                  DATETIME2 NULL,

        CONSTRAINT PK_TEMPLATE_GROUP_MAPPING PRIMARY KEY CLUSTERED (TEMPLATE_GROUP_MAPPING_ID),
        CONSTRAINT FK_TEMPLATE_GROUP_MAPPING_TEMPLATE FOREIGN KEY (CUSTOMIZATION_TEMPLATE_ID) 
            REFERENCES dbo.CUSTOMIZATION_TEMPLATES (CUSTOMIZATION_TEMPLATE_ID) ON DELETE CASCADE,
        CONSTRAINT FK_TEMPLATE_GROUP_MAPPING_GROUP FOREIGN KEY (CUSTOMIZATION_GROUP_ID) 
            REFERENCES dbo.CUSTOMIZATION_GROUPS (CUSTOMIZATION_GROUP_ID) ON DELETE CASCADE,
        CONSTRAINT UQ_TEMPLATE_GROUP_MAPPING UNIQUE NONCLUSTERED (CUSTOMIZATION_TEMPLATE_ID, CUSTOMIZATION_GROUP_ID)
    );

    CREATE NONCLUSTERED INDEX IX_TEMPLATE_GROUP_MAPPING_GROUP 
        ON dbo.TEMPLATE_GROUP_MAPPING (CUSTOMIZATION_GROUP_ID);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CUSTOMIZATION_OPTIONS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.CUSTOMIZATION_OPTIONS
    (
        CUSTOMIZATION_OPTION_ID BIGINT IDENTITY(1,1) NOT NULL,
        CUSTOMIZATION_GROUP_ID  BIGINT NOT NULL,
        OPTION_CODE             VARCHAR(50) NOT NULL,
        OPTION_NAME_EN          NVARCHAR(150) NOT NULL,
        OPTION_NAME_AR          NVARCHAR(150) NOT NULL,
        ADDITIONAL_PRICE        DECIMAL(18,2) NOT NULL DEFAULT 0.00,
        IS_ACTIVE               BIT NOT NULL DEFAULT 1,
        CREATED_AT              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT              DATETIME2 NULL,

        CONSTRAINT PK_CUSTOMIZATION_OPTIONS PRIMARY KEY CLUSTERED (CUSTOMIZATION_OPTION_ID),
        CONSTRAINT FK_CUSTOMIZATION_OPTIONS_GROUP FOREIGN KEY (CUSTOMIZATION_GROUP_ID) 
            REFERENCES dbo.CUSTOMIZATION_GROUPS (CUSTOMIZATION_GROUP_ID) ON DELETE CASCADE,
        CONSTRAINT UQ_CUSTOMIZATION_OPTIONS_GROUP_CODE UNIQUE NONCLUSTERED (CUSTOMIZATION_GROUP_ID, OPTION_CODE)
    );

    CREATE NONCLUSTERED INDEX IX_CUSTOMIZATION_OPTIONS_GROUP 
        ON dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, IS_ACTIVE);
END;
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PRODUCTS' AND schema_id = SCHEMA_ID('dbo'))
   AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PRODUCTS_CUSTOMIZATION_TEMPLATE')
BEGIN
    -- Clean up invalid / orphaned CUSTOMIZATION_TEMPLATE_ID values in PRODUCTS
    UPDATE p
    SET p.CUSTOMIZATION_TEMPLATE_ID = NULL
    FROM dbo.PRODUCTS p
    WHERE p.CUSTOMIZATION_TEMPLATE_ID IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 
          FROM dbo.CUSTOMIZATION_TEMPLATES ct 
          WHERE ct.CUSTOMIZATION_TEMPLATE_ID = p.CUSTOMIZATION_TEMPLATE_ID
      );

    ALTER TABLE dbo.PRODUCTS WITH CHECK
    ADD CONSTRAINT FK_PRODUCTS_CUSTOMIZATION_TEMPLATE FOREIGN KEY (CUSTOMIZATION_TEMPLATE_ID)
        REFERENCES dbo.CUSTOMIZATION_TEMPLATES (CUSTOMIZATION_TEMPLATE_ID);
END;
GO
