-- Migration: 0062_Remove_TemplateCode_From_CustomizationTemplates.sql
-- Description: Drops UQ_CUSTOMIZATION_TEMPLATES_CODE constraint and TEMPLATE_CODE column from dbo.CUSTOMIZATION_TEMPLATES if present.

IF EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = 'UQ_CUSTOMIZATION_TEMPLATES_CODE' AND parent_object_id = OBJECT_ID('dbo.CUSTOMIZATION_TEMPLATES'))
BEGIN
    ALTER TABLE dbo.CUSTOMIZATION_TEMPLATES DROP CONSTRAINT UQ_CUSTOMIZATION_TEMPLATES_CODE;
END;
GO

IF EXISTS (SELECT 1 FROM sys.columns WHERE name = 'TEMPLATE_CODE' AND object_id = OBJECT_ID('dbo.CUSTOMIZATION_TEMPLATES'))
BEGIN
    ALTER TABLE dbo.CUSTOMIZATION_TEMPLATES DROP COLUMN TEMPLATE_CODE;
END;
GO
