-- Migration: 0069_Seed_Default_Customization_Options.sql
-- Description: Seeds initial standard meat customization options into dbo.CUSTOMIZATION_OPTIONS.

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CUSTOMIZATION_OPTIONS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    DECLARE @CutTypeId BIGINT, @CleaningId BIGINT, @SkinTypeId BIGINT, @PackagingId BIGINT, @MarinationId BIGINT;

    SELECT @CutTypeId = CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'CUT_TYPE';
    SELECT @CleaningId = CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'CLEANING';
    SELECT @SkinTypeId = CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'SKIN_TYPE';
    SELECT @PackagingId = CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'PACKAGING';
    SELECT @MarinationId = CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'MARINATION';

    -- 1. CUT_TYPE Options
    IF @CutTypeId IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CutTypeId AND OPTION_CODE = 'CURRY_CUT')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CutTypeId, 'CURRY_CUT', N'Curry Cut (Medium Pieces)', N'تقطيع كاري (قطع متوسطة)', 0.00, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CutTypeId AND OPTION_CODE = 'BIRYANI_CUT')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CutTypeId, 'BIRYANI_CUT', N'Biryani Cut (Large Pieces)', N'تقطيع برياني (قطع كبيرة)', 0.50, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CutTypeId AND OPTION_CODE = 'MINCED_KEEMA')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CutTypeId, 'MINCED_KEEMA', N'Minced Meat (Keema)', N'مفروم (قيما)', 0.75, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CutTypeId AND OPTION_CODE = 'WHOLE_MEAT')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CutTypeId, 'WHOLE_MEAT', N'Whole Meat (Uncut)', N'لحم كامل (بدون تقطيع)', 0.00, 1);
    END;

    -- 2. CLEANING Options
    IF @CleaningId IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CleaningId AND OPTION_CODE = 'CLEAN_WASH')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CleaningId, 'CLEAN_WASH', N'Clean & Wash Thoroughly', N'تنظيف وغسيل جيد جداً', 0.00, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CleaningId AND OPTION_CODE = 'NO_WASH')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CleaningId, 'NO_WASH', N'No Washing Required', N'بدون غسيل', 0.00, 1);
    END;

    -- 3. SKIN_TYPE Options
    IF @SkinTypeId IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @SkinTypeId AND OPTION_CODE = 'SKINLESS')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@SkinTypeId, 'SKINLESS', N'Skinless', N'بدون جلد', 0.00, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @SkinTypeId AND OPTION_CODE = 'WITH_SKIN')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@SkinTypeId, 'WITH_SKIN', N'With Skin', N'مع الجلد', 0.00, 1);
    END;

    -- 4. PACKAGING Options
    IF @PackagingId IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @PackagingId AND OPTION_CODE = 'STANDARD_TRAY')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@PackagingId, 'STANDARD_TRAY', N'Standard Tray Packaging', N'تغليف طبق قياسي', 0.00, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @PackagingId AND OPTION_CODE = 'VACUUM_SEALED')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@PackagingId, 'VACUUM_SEALED', N'Vacuum Sealed Pack', N'تغليف مفرغ من الهواء', 0.75, 1);
    END;

    -- 5. MARINATION Options
    IF @MarinationId IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @MarinationId AND OPTION_CODE = 'PLAIN_NO_MARINATION')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@MarinationId, 'PLAIN_NO_MARINATION', N'Plain (No Marination)', N'سادة (بدون تتبيلة)', 0.00, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @MarinationId AND OPTION_CODE = 'ARABIC_SPICE_MARINADE')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@MarinationId, 'ARABIC_SPICE_MARINADE', N'Arabic Spices Marinade', N'تتبيلة البهارات العربية', 1.00, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @MarinationId AND OPTION_CODE = 'TANDOORI_MARINADE')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@MarinationId, 'TANDOORI_MARINADE', N'Tandoori Special Marinade', N'تتبيلة التنوري الخاصة', 1.25, 1);
    END;
END;
GO
