-- Migration: 0070_Seed_More_Customization_Options.sql
-- Description: Seeds additional detailed meat customization options into dbo.CUSTOMIZATION_OPTIONS.

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CUSTOMIZATION_OPTIONS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    DECLARE @CutTypeId BIGINT, @CleaningId BIGINT, @SkinTypeId BIGINT, @PackagingId BIGINT, @MarinationId BIGINT;

    SELECT @CutTypeId = CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'CUT_TYPE';
    SELECT @CleaningId = CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'CLEANING';
    SELECT @SkinTypeId = CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'SKIN_TYPE';
    SELECT @PackagingId = CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'PACKAGING';
    SELECT @MarinationId = CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'MARINATION';

    -- 1. CUT_TYPE Additions
    IF @CutTypeId IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CutTypeId AND OPTION_CODE = 'BONELESS')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CutTypeId, 'BONELESS', N'Boneless Cut', N'قطع بدون عظم', 1.50, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CutTypeId AND OPTION_CODE = 'CHOPS_CUT')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CutTypeId, 'CHOPS_CUT', N'Chops Cut', N'تقطيع ريش', 1.00, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CutTypeId AND OPTION_CODE = 'STRIPS_SLICES')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CutTypeId, 'STRIPS_SLICES', N'Strips & Slices', N'شرائح رفيعة', 1.00, 1);
    END;

    -- 2. CLEANING Additions
    IF @CleaningId IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CleaningId AND OPTION_CODE = 'DESCALED_GUTTED')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CleaningId, 'DESCALED_GUTTED', N'Descaled & Gutted', N'تنظيف وإزالة الأحشاء والقشور', 0.00, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @CleaningId AND OPTION_CODE = 'FAT_TRIMMED')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@CleaningId, 'FAT_TRIMMED', N'Extra Fat Trimmed', N'إزالة الدهون الإضافية', 0.50, 1);
    END;

    -- 3. SKIN_TYPE Additions
    IF @SkinTypeId IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @SkinTypeId AND OPTION_CODE = 'SEMI_SKINLESS')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@SkinTypeId, 'SEMI_SKINLESS', N'Semi Skinless (Wings Skin On)', N'جلد جزئي', 0.00, 1);
    END;

    -- 4. PACKAGING Additions
    IF @PackagingId IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @PackagingId AND OPTION_CODE = 'ZIPLOCK_POUCH')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@PackagingId, 'ZIPLOCK_POUCH', N'Ziplock Seal Pouch', N'كيس محكم الإغلاق', 0.25, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @PackagingId AND OPTION_CODE = 'ICE_PACK_INSULATED')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@PackagingId, 'ICE_PACK_INSULATED', N'Insulated Thermal Box with Ice Pack', N'صندوق حراري مع ثلج', 1.50, 1);
    END;

    -- 5. MARINATION Additions
    IF @MarinationId IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @MarinationId AND OPTION_CODE = 'GREEN_HERB_CHUTNEY')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@MarinationId, 'GREEN_HERB_CHUTNEY', N'Green Herb & Garlic Marinade', N'تتبيلة الأعشاب والثوم', 1.00, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @MarinationId AND OPTION_CODE = 'SMOKEY_BBQ')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@MarinationId, 'SMOKEY_BBQ', N'Smokey BBQ Marinade', N'تتبيلة باربيكيو مدخنة', 1.25, 1);

        IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @MarinationId AND OPTION_CODE = 'LEMON_PEPPER')
            INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
            VALUES (@MarinationId, 'LEMON_PEPPER', N'Lemon Pepper Marinade', N'تتبيلة الليمون والفلفل', 1.00, 1);
    END;
END;
GO
