-- ============================================================================
-- Migration: 0080_Create_Cart_Tables.sql
-- Description: Creates 3 Cart tables (CARTS, CART_ITEMS, CART_ITEM_CUSTOMIZATIONS),
--              indexes (UX_CARTS_ACTIVE_CUSTOMER, UX_CART_ITEMS_SIGNATURE), and constraints.
-- ============================================================================

-- 1. CARTS Table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CARTS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.CARTS
    (
        CART_ID          BIGINT IDENTITY(1,1) NOT NULL,
        DOCTYPE          VARCHAR(20)          NOT NULL,
        DOC_NO           VARCHAR(50)          NOT NULL,
        CUSTOMER_USER_ID BIGINT               NOT NULL,
        CART_STATUS      VARCHAR(20)          NOT NULL CONSTRAINT DF_CARTS_STATUS DEFAULT ('ACTIVE'),
        COUPON_ID        BIGINT               NULL,
        CREATED_AT       DATETIME2            NOT NULL CONSTRAINT DF_CARTS_CREATED DEFAULT (SYSUTCDATETIME()),
        UPDATED_AT       DATETIME2            NULL,

        CONSTRAINT PK_CARTS PRIMARY KEY CLUSTERED (CART_ID),
        CONSTRAINT UQ_CARTS_DOC_NO UNIQUE NONCLUSTERED (DOC_NO),
        CONSTRAINT FK_CARTS_CUSTOMER FOREIGN KEY (CUSTOMER_USER_ID) REFERENCES dbo.CUSTOMER_USERS (USER_ID)
    );

    -- Filtered Unique Index: One ACTIVE cart per customer
    CREATE UNIQUE NONCLUSTERED INDEX UX_CARTS_ACTIVE_CUSTOMER
        ON dbo.CARTS (CUSTOMER_USER_ID)
        WHERE CART_STATUS = 'ACTIVE';

    CREATE NONCLUSTERED INDEX IX_CARTS_STATUS
        ON dbo.CARTS (CART_STATUS);
END;

-- 2. CART_ITEMS Table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CART_ITEMS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.CART_ITEMS
    (
        CART_ITEM_ID         BIGINT IDENTITY(1,1) NOT NULL,
        CART_ID              BIGINT               NOT NULL,
        DOC_NO               VARCHAR(50)          NOT NULL,
        PRODUCT_ID           BIGINT               NOT NULL,
        QUANTITY             INT                  NOT NULL CONSTRAINT DF_CART_ITEMS_QTY DEFAULT (1),
        SPECIAL_INSTRUCTIONS NVARCHAR(1000)       NULL,
        ITEM_STATUS          VARCHAR(20)          NOT NULL CONSTRAINT DF_CART_ITEMS_STATUS DEFAULT ('ACTIVE'),
        ITEM_SIGNATURE       VARCHAR(100)         NOT NULL,
        CREATED_AT           DATETIME2            NOT NULL CONSTRAINT DF_CART_ITEMS_CREATED DEFAULT (SYSUTCDATETIME()),
        UPDATED_AT           DATETIME2            NULL,

        CONSTRAINT PK_CART_ITEMS PRIMARY KEY CLUSTERED (CART_ITEM_ID),
        CONSTRAINT FK_CART_ITEMS_CART FOREIGN KEY (CART_ID) REFERENCES dbo.CARTS (CART_ID) ON DELETE CASCADE,
        CONSTRAINT FK_CART_ITEMS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCTS (PRODUCT_ID),
        CONSTRAINT CK_CART_ITEMS_QUANTITY CHECK (QUANTITY > 0)
    );

    -- Unique Constraint: (CART_ID, ITEM_SIGNATURE) to enforce signature line merging
    CREATE UNIQUE NONCLUSTERED INDEX UX_CART_ITEMS_SIGNATURE
        ON dbo.CART_ITEMS (CART_ID, ITEM_SIGNATURE);

    CREATE NONCLUSTERED INDEX IX_CART_ITEMS_STATUS
        ON dbo.CART_ITEMS (ITEM_STATUS);
END;

-- 3. CART_ITEM_CUSTOMIZATIONS Table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CART_ITEM_CUSTOMIZATIONS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.CART_ITEM_CUSTOMIZATIONS
    (
        CART_ITEM_CUSTOMIZATION_ID BIGINT IDENTITY(1,1) NOT NULL,
        CART_ITEM_ID               BIGINT               NOT NULL,
        DOC_NO                     VARCHAR(50)          NOT NULL,
        CUSTOMIZATION_OPTION_ID    BIGINT               NOT NULL,
        CREATED_AT                 DATETIME2            NOT NULL CONSTRAINT DF_CART_ITEM_CUST_CREATED DEFAULT (SYSUTCDATETIME()),

        CONSTRAINT PK_CART_ITEM_CUSTOMIZATIONS PRIMARY KEY CLUSTERED (CART_ITEM_CUSTOMIZATION_ID),
        CONSTRAINT FK_CART_ITEM_CUST_ITEM FOREIGN KEY (CART_ITEM_ID) REFERENCES dbo.CART_ITEMS (CART_ITEM_ID) ON DELETE CASCADE,
        CONSTRAINT FK_CART_ITEM_CUST_OPTION FOREIGN KEY (CUSTOMIZATION_OPTION_ID) REFERENCES dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_OPTION_ID)
    );

    -- Unique Constraint: (CART_ITEM_ID, CUSTOMIZATION_OPTION_ID) prevents duplicate options on same item
    CREATE UNIQUE NONCLUSTERED INDEX UX_CART_ITEM_CUSTOMIZATIONS
        ON dbo.CART_ITEM_CUSTOMIZATIONS (CART_ITEM_ID, CUSTOMIZATION_OPTION_ID);
END;
GO
