-- Migration Script: 0087_Support_Configurable_Customization_Pricing.sql
-- Description: Add PRICING_TYPE and PRICING_VALUE to CUSTOMIZATION_GROUPS.

-- 1. Add PRICING_TYPE column to CUSTOMIZATION_GROUPS
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'dbo.CUSTOMIZATION_GROUPS') AND name = 'PRICING_TYPE')
BEGIN
    ALTER TABLE dbo.CUSTOMIZATION_GROUPS
    ADD PRICING_TYPE VARCHAR(20) NOT NULL CONSTRAINT DF_GROUPS_PRICING_TYPE DEFAULT ('ADDITIONAL_PRICE');
END;
GO

-- 2. Add Constraint to PRICING_TYPE
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_GROUPS_PRICING_TYPE')
BEGIN
    ALTER TABLE dbo.CUSTOMIZATION_GROUPS
    ADD CONSTRAINT CK_GROUPS_PRICING_TYPE CHECK (PRICING_TYPE IN ('ADDITIONAL_PRICE', 'MULTIPLIER', 'FIXED_PRICE', 'PERCENTAGE'));
END;
GO

-- 3. Add PRICING_VALUE column to CUSTOMIZATION_GROUPS
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'dbo.CUSTOMIZATION_GROUPS') AND name = 'PRICING_VALUE')
BEGIN
    ALTER TABLE dbo.CUSTOMIZATION_GROUPS
    ADD PRICING_VALUE DECIMAL(18,2) NOT NULL CONSTRAINT DF_GROUPS_PRICING_VALUE DEFAULT (0.00);
END;
GO
