-- Migration Script: 0089_Update_Customization_Groups_Pricing_Types.sql
-- Description: Seed/Update customization groups with diverse pricing types (MULTIPLIER, PERCENTAGE, FIXED_PRICE, ADDITIONAL_PRICE).

-- 1. Ensure 'WEIGHT' group exists with MULTIPLIER pricing type
IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'WEIGHT')
BEGIN
    INSERT INTO dbo.CUSTOMIZATION_GROUPS (GROUP_CODE, GROUP_NAME_EN, GROUP_NAME_AR, IS_ADDITIONAL_PRICE_AVAILABLE, PRICING_TYPE, PRICING_VALUE, IS_ACTIVE, CREATED_AT)
    VALUES ('WEIGHT', 'Weight Selection', N'اختيار الوزن', 1, 'MULTIPLIER', 1.00, 1, SYSUTCDATETIME());
END
ELSE
BEGIN
    UPDATE dbo.CUSTOMIZATION_GROUPS
    SET PRICING_TYPE = 'MULTIPLIER', PRICING_VALUE = 1.00, UPDATED_AT = SYSUTCDATETIME()
    WHERE GROUP_CODE = 'WEIGHT';
END;
GO

-- 2. Ensure Options exist for 'WEIGHT' (2 KG -> x2, 5 KG -> x5, 10 KG -> x10)
DECLARE @WeightGroupId BIGINT = (SELECT CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'WEIGHT');

IF @WeightGroupId IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @WeightGroupId AND OPTION_CODE = 'WEIGHT_2KG')
    BEGIN
        INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
        VALUES (@WeightGroupId, 'WEIGHT_2KG', '2 KG', N'2 كيلو', 2.00, 1);
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @WeightGroupId AND OPTION_CODE = 'WEIGHT_5KG')
    BEGIN
        INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
        VALUES (@WeightGroupId, 'WEIGHT_5KG', '5 KG', N'5 كيلو', 5.00, 1);
    END;

    IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @WeightGroupId AND OPTION_CODE = 'WEIGHT_10KG')
    BEGIN
        INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
        VALUES (@WeightGroupId, 'WEIGHT_10KG', '10 KG', N'10 كيلو', 10.00, 1);
    END;
END;
GO

-- 3. Ensure 'PREMIUM_CUT' group exists with PERCENTAGE pricing type (+10%)
IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'PREMIUM_CUT')
BEGIN
    INSERT INTO dbo.CUSTOMIZATION_GROUPS (GROUP_CODE, GROUP_NAME_EN, GROUP_NAME_AR, IS_ADDITIONAL_PRICE_AVAILABLE, PRICING_TYPE, PRICING_VALUE, IS_ACTIVE, CREATED_AT)
    VALUES ('PREMIUM_CUT', 'Premium Cut', N'قطع مميز', 1, 'PERCENTAGE', 10.00, 1, SYSUTCDATETIME());
END
ELSE
BEGIN
    UPDATE dbo.CUSTOMIZATION_GROUPS
    SET PRICING_TYPE = 'PERCENTAGE', PRICING_VALUE = 10.00, UPDATED_AT = SYSUTCDATETIME()
    WHERE GROUP_CODE = 'PREMIUM_CUT';
END;
GO

DECLARE @PremiumGroupId BIGINT = (SELECT CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'PREMIUM_CUT');

IF @PremiumGroupId IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @PremiumGroupId AND OPTION_CODE = 'PREMIUM_CUT_OPTION')
    BEGIN
        INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
        VALUES (@PremiumGroupId, 'PREMIUM_CUT_OPTION', 'Premium (+10%)', N'ممتاز (+10%)', 10.00, 1);
    END;
END;
GO

-- 4. Ensure 'SPECIAL_PACKAGE' group exists with FIXED_PRICE pricing type ($50)
IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'SPECIAL_PACKAGE')
BEGIN
    INSERT INTO dbo.CUSTOMIZATION_GROUPS (GROUP_CODE, GROUP_NAME_EN, GROUP_NAME_AR, IS_ADDITIONAL_PRICE_AVAILABLE, PRICING_TYPE, PRICING_VALUE, IS_ACTIVE, CREATED_AT)
    VALUES ('SPECIAL_PACKAGE', 'Special Package', N'باقة خاصة', 1, 'FIXED_PRICE', 50.00, 1, SYSUTCDATETIME());
END
ELSE
BEGIN
    UPDATE dbo.CUSTOMIZATION_GROUPS
    SET PRICING_TYPE = 'FIXED_PRICE', PRICING_VALUE = 50.00, UPDATED_AT = SYSUTCDATETIME()
    WHERE GROUP_CODE = 'SPECIAL_PACKAGE';
END;
GO

DECLARE @SpecialPackageGroupId BIGINT = (SELECT CUSTOMIZATION_GROUP_ID FROM dbo.CUSTOMIZATION_GROUPS WHERE GROUP_CODE = 'SPECIAL_PACKAGE');

IF @SpecialPackageGroupId IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_OPTIONS WHERE CUSTOMIZATION_GROUP_ID = @SpecialPackageGroupId AND OPTION_CODE = 'FAMILY_PACK')
    BEGIN
        INSERT INTO dbo.CUSTOMIZATION_OPTIONS (CUSTOMIZATION_GROUP_ID, OPTION_CODE, OPTION_NAME_EN, OPTION_NAME_AR, ADDITIONAL_PRICE, IS_ACTIVE)
        VALUES (@SpecialPackageGroupId, 'FAMILY_PACK', 'Family Pack ($50)', N'باقة العائلة ($50)', 50.00, 1);
    END;
END;
GO

-- 5. Map new groups to existing default template (CUSTOMIZATION_TEMPLATE_ID = 1)
IF EXISTS (SELECT 1 FROM dbo.CUSTOMIZATION_TEMPLATES WHERE CUSTOMIZATION_TEMPLATE_ID = 1)
BEGIN
    INSERT INTO dbo.TEMPLATE_GROUP_MAPPING (CUSTOMIZATION_TEMPLATE_ID, CUSTOMIZATION_GROUP_ID, IS_ACTIVE)
    SELECT 1, cg.CUSTOMIZATION_GROUP_ID, 1
    FROM dbo.CUSTOMIZATION_GROUPS cg
    WHERE cg.GROUP_CODE IN ('WEIGHT', 'PREMIUM_CUT', 'SPECIAL_PACKAGE')
      AND NOT EXISTS (
          SELECT 1 FROM dbo.TEMPLATE_GROUP_MAPPING m 
          WHERE m.CUSTOMIZATION_TEMPLATE_ID = 1 AND m.CUSTOMIZATION_GROUP_ID = cg.CUSTOMIZATION_GROUP_ID
      );
END;
GO
