-- Migration Script: 0097_Add_Selected_Value_To_Cart_Item_Customizations.sql
-- Description: Add SELECTED_VALUE DECIMAL(18,3) NULL to dbo.CART_ITEM_CUSTOMIZATIONS and create dbo.TT_CUSTOMIZATION_SELECTIONS table type.

-- 1. Add SELECTED_VALUE column to dbo.CART_ITEM_CUSTOMIZATIONS
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'dbo.CART_ITEM_CUSTOMIZATIONS') AND name = 'SELECTED_VALUE')
BEGIN
    ALTER TABLE dbo.CART_ITEM_CUSTOMIZATIONS
    ADD SELECTED_VALUE DECIMAL(18,3) NULL;
END;
GO

-- 2. Create User-Defined Table Type dbo.TT_CUSTOMIZATION_SELECTIONS
IF NOT EXISTS (SELECT 1 FROM sys.types WHERE name = 'TT_CUSTOMIZATION_SELECTIONS' AND is_user_defined = 1)
BEGIN
    CREATE TYPE dbo.TT_CUSTOMIZATION_SELECTIONS AS TABLE
    (
        OPTION_ID      BIGINT         NOT NULL,
        SELECTED_VALUE DECIMAL(18,3) NULL
    );
END;
GO
