-- =============================================================================
-- MIGRATION SCRIPT: 0122_Create_Orders_And_Payment_Tables.sql
-- Description: Creates ORDERS, ORDER_ITEMS, ORDER_ITEM_CUSTOMIZATIONS, ORDER_STATUS_HISTORY, PAYMENT_TRANSACTIONS tables and PR_PREVIEW_CUSTOMER_ORDER SP.
-- =============================================================================

-- 1. Ensure ORD1 Document Type in M_DOC_NO
IF NOT EXISTS (SELECT 1 FROM dbo.M_DOC_NO WHERE DOCTYPE = 'ORD1')
BEGIN
    DECLARE @CompanyId BIGINT = (SELECT TOP 1 COMPANY_CONFIG_ID FROM dbo.COMPANY_CONFIG WHERE IS_ACTIVE = 1);
    
    INSERT INTO dbo.M_DOC_NO 
    (MDOC, DOCTYPE, DESCRIPTION, COMPANY_CONFIG_ID, PREFIX, SUFFIX, DIGIT_NO, START_DOCNO, PERIODWISE_YN, PERIOD_TYPE, IS_ACTIVE)
    VALUES 
    ('ORD', 'ORD1', 'Order Master Document', @CompanyId, 'ORD-', '', 6, 1, 'N', 'NONE', 1);
END;
GO

-- 2. Create ORDERS Table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ORDERS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.ORDERS
    (
        ORDER_ID                    BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        DOCTYPE                     VARCHAR(20)          NOT NULL CONSTRAINT FK_ORDERS_DOCTYPE REFERENCES dbo.M_DOC_NO(DOCTYPE),
        DOC_NO                      VARCHAR(50)          NOT NULL,
        CUSTOMER_USER_ID            BIGINT               NOT NULL CONSTRAINT FK_ORDERS_CUSTOMER REFERENCES dbo.CUSTOMER_USERS(USER_ID),
        CART_ID                     BIGINT               NULL CONSTRAINT FK_ORDERS_CART REFERENCES dbo.CARTS(CART_ID),
        ADDRESS_ID                  BIGINT               NULL CONSTRAINT FK_ORDERS_ADDRESS REFERENCES dbo.CUSTOMER_ADDRESSES(ADDRESS_ID) ON DELETE SET NULL,
        
        DELIVERY_CONTACT_NUMBER     VARCHAR(30)          NOT NULL,
        DELIVERY_ADDRESS_TYPE       VARCHAR(20)          NULL,
        DELIVERY_BUILDING_NAME      NVARCHAR(150)        NULL,
        DELIVERY_VILLA_OR_FLAT_NO   NVARCHAR(50)         NOT NULL,
        DELIVERY_STREET             NVARCHAR(200)        NOT NULL,
        DELIVERY_AREA               NVARCHAR(150)        NOT NULL,
        DELIVERY_CITY               NVARCHAR(100)        NOT NULL,
        DELIVERY_LANDMARK           NVARCHAR(250)        NULL,
        DELIVERY_POSTAL_CODE        VARCHAR(20)          NULL,
        DELIVERY_EMIRATE            NVARCHAR(100)        NOT NULL,
        DELIVERY_LATITUDE           DECIMAL(10,7)        NULL,
        DELIVERY_LONGITUDE          DECIMAL(10,7)        NULL,
        DELIVERY_INSTRUCTIONS       NVARCHAR(500)        NULL,

        DELIVERY_DATE               DATE                 NOT NULL,
        DELIVERY_SLOT_START_TIME    TIME                 NOT NULL,
        DELIVERY_SLOT_END_TIME      TIME                 NOT NULL,

        ORDER_STATUS                VARCHAR(30)          NOT NULL DEFAULT 'PLACED',
        PAYMENT_METHOD              VARCHAR(20)          NOT NULL,
        PAYMENT_STATUS              VARCHAR(30)          NOT NULL DEFAULT 'PENDING',
        CURRENCY_CODE               VARCHAR(3)           NOT NULL DEFAULT 'AED',

        SUBTOTAL                    DECIMAL(18,2)        NOT NULL,
        PRODUCT_DISCOUNT_TOTAL      DECIMAL(18,2)        NOT NULL DEFAULT 0.00,
        COUPON_ID                   BIGINT               NULL,
        COUPON_DISCOUNT             DECIMAL(18,2)        NOT NULL DEFAULT 0.00,
        DELIVERY_CHARGE             DECIMAL(18,2)        NOT NULL DEFAULT 0.00,
        VAT_AMOUNT                  DECIMAL(18,2)        NOT NULL DEFAULT 0.00,
        TOTAL_AMOUNT                DECIMAL(18,2)        NOT NULL,

        CANCELLED_AT                DATETIME2            NULL,
        CANCELLATION_REASON         NVARCHAR(500)        NULL,
        PLACED_AT                   DATETIME2            NOT NULL DEFAULT SYSUTCDATETIME(),
        CREATED_AT                  DATETIME2            NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT                  DATETIME2            NULL,

        CONSTRAINT UQ_ORDERS_DOCTYPE_DOCNO UNIQUE (DOCTYPE, DOC_NO)
    );

    CREATE NONCLUSTERED INDEX IX_ORDERS_CUSTOMER ON dbo.ORDERS(CUSTOMER_USER_ID, CREATED_AT DESC);
    CREATE NONCLUSTERED INDEX IX_ORDERS_STATUS ON dbo.ORDERS(ORDER_STATUS);
END;
GO

-- 3. Create ORDER_ITEMS Table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ORDER_ITEMS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.ORDER_ITEMS
    (
        ORDER_ITEM_ID               BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ORDER_ID                    BIGINT               NOT NULL CONSTRAINT FK_ORDER_ITEMS_ORDER REFERENCES dbo.ORDERS(ORDER_ID),
        DOC_NO                      VARCHAR(50)          NOT NULL,
        PRODUCT_ID                  BIGINT               NOT NULL CONSTRAINT FK_ORDER_ITEMS_PRODUCT REFERENCES dbo.PRODUCTS(PRODUCT_ID),
        PRODUCT_CODE                VARCHAR(50)          NOT NULL,
        PRODUCT_NAME_EN             NVARCHAR(200)        NOT NULL,
        PRODUCT_NAME_AR             NVARCHAR(200)        NOT NULL,
        UNIT_DESCRIPTION            VARCHAR(50)          NOT NULL,

        REGULAR_UNIT_PRICE          DECIMAL(18,2)        NOT NULL,
        SELLING_UNIT_PRICE          DECIMAL(18,2)        NOT NULL,
        CUSTOMIZATION_UNIT_PRICE    DECIMAL(18,2)        NOT NULL DEFAULT 0.00,
        QUANTITY                    INT                  NOT NULL CHECK (QUANTITY > 0),
        LINE_SUBTOTAL               DECIMAL(18,2)        NOT NULL,
        PRODUCT_DISCOUNT_AMOUNT     DECIMAL(18,2)        NOT NULL DEFAULT 0.00,
        LINE_TOTAL                  DECIMAL(18,2)        NOT NULL,

        SPECIAL_INSTRUCTIONS        NVARCHAR(1000)        NULL,
        OFFER_ID                    BIGINT               NULL,
        CREATED_AT                  DATETIME2            NOT NULL DEFAULT SYSUTCDATETIME()
    );

    CREATE NONCLUSTERED INDEX IX_ORDER_ITEMS_ORDER ON dbo.ORDER_ITEMS(ORDER_ID);
END;
GO

-- 4. Create ORDER_ITEM_CUSTOMIZATIONS Table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ORDER_ITEM_CUSTOMIZATIONS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.ORDER_ITEM_CUSTOMIZATIONS
    (
        ORDER_ITEM_CUSTOMIZATION_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ORDER_ITEM_ID               BIGINT               NOT NULL CONSTRAINT FK_ORDER_ITEM_CUST_ITEM REFERENCES dbo.ORDER_ITEMS(ORDER_ITEM_ID),
        DOC_NO                      VARCHAR(50)          NOT NULL,
        CUSTOMIZATION_OPTION_ID     BIGINT               NOT NULL CONSTRAINT FK_ORDER_ITEM_CUST_OPTION REFERENCES dbo.CUSTOMIZATION_OPTIONS(CUSTOMIZATION_OPTION_ID),
        GROUP_NAME_EN               NVARCHAR(150)        NOT NULL,
        GROUP_NAME_AR               NVARCHAR(150)        NOT NULL,
        OPTION_NAME_EN              NVARCHAR(150)        NOT NULL,
        OPTION_NAME_AR              NVARCHAR(150)        NOT NULL,
        ADDITIONAL_PRICE            DECIMAL(18,2)        NOT NULL DEFAULT 0.00,
        CREATED_AT                  DATETIME2            NOT NULL DEFAULT SYSUTCDATETIME(),

        CONSTRAINT UQ_ORDER_ITEM_CUSTOMIZATION UNIQUE (ORDER_ITEM_ID, CUSTOMIZATION_OPTION_ID)
    );
END;
GO

-- 5. Create ORDER_STATUS_HISTORY Table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ORDER_STATUS_HISTORY' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.ORDER_STATUS_HISTORY
    (
        ORDER_STATUS_HISTORY_ID     BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ORDER_ID                    BIGINT               NOT NULL CONSTRAINT FK_ORDER_STATUS_HISTORY_ORDER REFERENCES dbo.ORDERS(ORDER_ID),
        DOC_NO                      VARCHAR(50)          NOT NULL,
        ORDER_STATUS                VARCHAR(30)          NOT NULL,
        REMARKS                     NVARCHAR(500)        NULL,
        CHANGED_BY_ADMIN_USER_ID    BIGINT               NULL CONSTRAINT FK_ORDER_STATUS_HISTORY_ADMIN REFERENCES dbo.ADMIN_USERS(ADMIN_USER_ID),
        CREATED_AT                  DATETIME2            NOT NULL DEFAULT SYSUTCDATETIME()
    );

    CREATE NONCLUSTERED INDEX IX_ORDER_STATUS_HISTORY_ORDER ON dbo.ORDER_STATUS_HISTORY(ORDER_ID, CREATED_AT ASC);
END;
GO

-- 6. Create PAYMENT_TRANSACTIONS Table
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PAYMENT_TRANSACTIONS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.PAYMENT_TRANSACTIONS
    (
        PAYMENT_TRANSACTION_ID      BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        DOCTYPE                     VARCHAR(20)          NOT NULL CONSTRAINT FK_PAY_TRANS_DOCTYPE REFERENCES dbo.M_DOC_NO(DOCTYPE),
        DOC_NO                      VARCHAR(50)          NOT NULL,
        ORDER_ID                    BIGINT               NOT NULL CONSTRAINT FK_PAY_TRANS_ORDER REFERENCES dbo.ORDERS(ORDER_ID),
        PARENT_TRANSACTION_ID       BIGINT               NULL CONSTRAINT FK_PAY_TRANS_PARENT REFERENCES dbo.PAYMENT_TRANSACTIONS(PAYMENT_TRANSACTION_ID),
        TRANSACTION_TYPE            VARCHAR(20)          NOT NULL CHECK (TRANSACTION_TYPE IN ('PAYMENT', 'REFUND')),
        PAYMENT_METHOD              VARCHAR(20)          NOT NULL CHECK (PAYMENT_METHOD IN ('CARD', 'APPLE_PAY', 'GOOGLE_PAY', 'COD', 'WALLET')),
        PAYMENT_PROVIDER            VARCHAR(50)          NULL,
        GATEWAY_TRANSACTION_ID      VARCHAR(150)         NULL,
        GATEWAY_REFERENCE           VARCHAR(150)         NULL,
        IDEMPOTENCY_KEY             VARCHAR(100)         NULL,
        AMOUNT                      DECIMAL(18,2)        NOT NULL CHECK (AMOUNT > 0),
        CURRENCY_CODE               VARCHAR(3)           NOT NULL DEFAULT 'AED',
        TRANSACTION_STATUS          VARCHAR(20)          NOT NULL CHECK (TRANSACTION_STATUS IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED')),
        FAILURE_CODE                VARCHAR(100)         NULL,
        FAILURE_MESSAGE             NVARCHAR(500)        NULL,
        PROCESSED_AT                DATETIME2            NULL,
        CREATED_AT                  DATETIME2            NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT                  DATETIME2            NULL,

        CONSTRAINT UQ_PAY_TRANS_DOCTYPE_DOCNO UNIQUE (DOCTYPE, DOC_NO)
    );

    CREATE NONCLUSTERED INDEX IX_PAY_TRANS_ORDER ON dbo.PAYMENT_TRANSACTIONS(ORDER_ID, CREATED_AT);
END;
GO

-- 7. Create Procedure: dbo.PR_PREVIEW_CUSTOMER_ORDER
CREATE OR ALTER PROCEDURE dbo.PR_PREVIEW_CUSTOMER_ORDER
(
    @CUSTOMER_USER_ID BIGINT,
    @ADDRESS_ID       BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    -- A. Company Config Coordinates & Delivery Rates
    SELECT TOP 1
        COMPANY_CONFIG_ID,
        COMPANY_NAME_EN,
        LATITUDE AS STORE_LATITUDE,
        LONGITUDE AS STORE_LONGITUDE,
        ADVANCE_DELIVERY_DAYS,
        DELIVERY_START_TIME,
        DELIVERY_END_TIME
    FROM dbo.COMPANY_CONFIG
    WHERE IS_ACTIVE = 1;

    -- B. Customer Address Details
    SELECT
        ADDRESS_ID,
        CUSTOMER_USER_ID,
        FIRST_NAME,
        LAST_NAME,
        ADDRESS_TYPE,
        CONTACT_NUMBER,
        BUILDING_NAME,
        VILLA_OR_FLAT_NO,
        STREET,
        AREA,
        LANDMARK,
        CITY,
        POSTAL_CODE,
        LATITUDE,
        LONGITUDE,
        IS_DEFAULT
    FROM dbo.CUSTOMER_ADDRESSES
    WHERE ADDRESS_ID = @ADDRESS_ID
      AND CUSTOMER_USER_ID = @CUSTOMER_USER_ID
      AND IS_ACTIVE = 1;

    -- C. Customer Active Cart Header
    SELECT 
        c.CART_ID,
        c.CUSTOMER_USER_ID,
        c.CART_STATUS,
        c.COUPON_ID,
        c.CREATED_AT
    FROM dbo.CARTS c
    WHERE c.CUSTOMER_USER_ID = @CUSTOMER_USER_ID
      AND c.CART_STATUS = 'ACTIVE';

    -- D. Cart Items with Product Pricing Snapshots
    SELECT 
        ci.CART_ITEM_ID,
        ci.CART_ID,
        ci.PRODUCT_ID,
        p.DOC_NO AS PRODUCT_CODE,
        p.PRODUCT_NAME_EN,
        p.PRODUCT_NAME_AR,
        img.PRIMARY_URL AS PRODUCT_IMAGE,
        ISNULL(u.UNIT_DESCRIPTION, 'Kilogram') AS UNIT_DESCRIPTION,
        ISNULL(pr.PRICE, 0.00) AS REGULAR_UNIT_PRICE,
        ISNULL(pr.PRICE, 0.00) AS SELLING_UNIT_PRICE,
        ci.QUANTITY,
        ci.SPECIAL_INSTRUCTIONS,
        ci.ITEM_STATUS
    FROM dbo.CART_ITEMS ci
    INNER JOIN dbo.CARTS c ON c.CART_ID = ci.CART_ID
    INNER JOIN dbo.PRODUCTS p ON p.PRODUCT_ID = ci.PRODUCT_ID
    LEFT JOIN dbo.MEASUREMENT_UNITS u ON u.UNIT_ID = p.UNIT_ID
    LEFT JOIN dbo.PRODUCT_PRICES pr ON pr.PRODUCT_ID = p.PRODUCT_ID AND pr.IS_ACTIVE = 1
    LEFT JOIN dbo.PRODUCT_IMAGES img ON img.PRODUCT_ID = p.PRODUCT_ID
    WHERE c.CUSTOMER_USER_ID = @CUSTOMER_USER_ID
      AND c.CART_STATUS = 'ACTIVE'
      AND ci.ITEM_STATUS = 'ACTIVE';

    -- E. Cart Item Customizations with Price Snapshots
    SELECT 
        cic.CART_ITEM_ID,
        co.CUSTOMIZATION_OPTION_ID,
        cg.GROUP_NAME_EN,
        cg.GROUP_NAME_AR,
        co.OPTION_CODE,
        co.OPTION_NAME_EN,
        co.OPTION_NAME_AR,
        ISNULL(co.PRICING_VALUE, 0.00) AS ADDITIONAL_PRICE
    FROM dbo.CART_ITEM_CUSTOMIZATIONS cic
    INNER JOIN dbo.CART_ITEMS ci ON ci.CART_ITEM_ID = cic.CART_ITEM_ID
    INNER JOIN dbo.CARTS c ON c.CART_ID = ci.CART_ID
    INNER JOIN dbo.CUSTOMIZATION_OPTIONS co ON co.CUSTOMIZATION_OPTION_ID = cic.CUSTOMIZATION_OPTION_ID
    INNER JOIN dbo.CUSTOMIZATION_GROUPS cg ON cg.CUSTOMIZATION_GROUP_ID = co.CUSTOMIZATION_GROUP_ID
    WHERE c.CUSTOMER_USER_ID = @CUSTOMER_USER_ID
      AND c.CART_STATUS = 'ACTIVE'
      AND ci.ITEM_STATUS = 'ACTIVE';
END;
GO
