-- 1. Add Audit and Soft Delete Columns if not exists
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.COUPONS') AND name = 'CREATED_BY')
BEGIN
    ALTER TABLE dbo.COUPONS ADD CREATED_BY BIGINT NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.COUPONS') AND name = 'UPDATED_BY')
BEGIN
    ALTER TABLE dbo.COUPONS ADD UPDATED_BY BIGINT NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.COUPONS') AND name = 'IS_DELETED')
BEGIN
    ALTER TABLE dbo.COUPONS ADD IS_DELETED BIT NOT NULL CONSTRAINT DF_COUPONS_IS_DELETED DEFAULT (0);
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.COUPONS') AND name = 'DELETED_AT')
BEGIN
    ALTER TABLE dbo.COUPONS ADD DELETED_AT DATETIME2 NULL;
END;
GO

-- 2. Update dbo.PR_SAVE_COUPON Stored Procedure
CREATE OR ALTER PROCEDURE dbo.PR_SAVE_COUPON
    @MODE                   VARCHAR(10),        -- 'ADD', 'EDIT', 'DELETE'
    @COUPON_ID              BIGINT = NULL,
    @COUPON_CODE            VARCHAR(50) = NULL,
    @DISCOUNT_TYPE          VARCHAR(20) = NULL, -- 'PERCENTAGE', 'FLAT'
    @DISCOUNT_VALUE         DECIMAL(18,2) = NULL,
    @MAX_DISCOUNT_AMOUNT    DECIMAL(18,2) = NULL,
    @MINIMUM_ORDER_AMOUNT   DECIMAL(18,2) = 0.00,
    @VALID_FROM             DATETIME2 = NULL,
    @VALID_TO               DATETIME2 = NULL,
    @USAGE_LIMIT_TOTAL      INT = NULL,
    @USAGE_LIMIT_PER_USER   INT = NULL,
    @COUPON_STATUS          VARCHAR(20) = 'ACTIVE',
    @COUPON_DESC            NVARCHAR(500) = NULL,
    @ACTIONED_BY            BIGINT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF UPPER(@MODE) = 'ADD'
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.COUPONS WHERE COUPON_CODE = @COUPON_CODE AND IS_DELETED = 0)
        BEGIN
            RAISERROR('Coupon code already exists.', 16, 1);
            RETURN;
        END

        INSERT INTO dbo.COUPONS
        (
            COUPON_CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, MAX_DISCOUNT_AMOUNT,
            MINIMUM_ORDER_AMOUNT, VALID_FROM, VALID_TO, USAGE_LIMIT_TOTAL,
            USAGE_LIMIT_PER_USER, COUPON_STATUS, COUPON_DESC, CREATED_BY, CREATED_AT, IS_DELETED
        )
        VALUES
        (
            UPPER(@COUPON_CODE), @DISCOUNT_TYPE, @DISCOUNT_VALUE, @MAX_DISCOUNT_AMOUNT,
            ISNULL(@MINIMUM_ORDER_AMOUNT, 0.00), @VALID_FROM, @VALID_TO, @USAGE_LIMIT_TOTAL,
            @USAGE_LIMIT_PER_USER, ISNULL(@COUPON_STATUS, 'ACTIVE'), @COUPON_DESC, @ACTIONED_BY, SYSUTCDATETIME(), 0
        );

        SET @COUPON_ID = SCOPE_IDENTITY();
    END
    ELSE IF UPPER(@MODE) = 'EDIT'
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.COUPONS WHERE COUPON_ID = @COUPON_ID AND IS_DELETED = 0)
        BEGIN
            RAISERROR('Coupon record not found.', 16, 1);
            RETURN;
        END

        UPDATE dbo.COUPONS
        SET COUPON_CODE          = ISNULL(@COUPON_CODE, COUPON_CODE),
            DISCOUNT_TYPE        = ISNULL(@DISCOUNT_TYPE, DISCOUNT_TYPE),
            DISCOUNT_VALUE       = ISNULL(@DISCOUNT_VALUE, DISCOUNT_VALUE),
            MAX_DISCOUNT_AMOUNT  = ISNULL(@MAX_DISCOUNT_AMOUNT, MAX_DISCOUNT_AMOUNT),
            MINIMUM_ORDER_AMOUNT = ISNULL(@MINIMUM_ORDER_AMOUNT, MINIMUM_ORDER_AMOUNT),
            VALID_FROM           = ISNULL(@VALID_FROM, VALID_FROM),
            VALID_TO             = ISNULL(@VALID_TO, VALID_TO),
            USAGE_LIMIT_TOTAL    = ISNULL(@USAGE_LIMIT_TOTAL, USAGE_LIMIT_TOTAL),
            USAGE_LIMIT_PER_USER = ISNULL(@USAGE_LIMIT_PER_USER, USAGE_LIMIT_PER_USER),
            COUPON_STATUS        = ISNULL(@COUPON_STATUS, COUPON_STATUS),
            COUPON_DESC          = ISNULL(@COUPON_DESC, COUPON_DESC),
            UPDATED_BY           = @ACTIONED_BY,
            UPDATED_AT           = SYSUTCDATETIME()
        WHERE COUPON_ID = @COUPON_ID AND IS_DELETED = 0;
    END
    ELSE IF UPPER(@MODE) = 'DELETE'
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.COUPONS WHERE COUPON_ID = @COUPON_ID AND IS_DELETED = 0)
        BEGIN
            RAISERROR('Coupon record not found or already deleted.', 16, 1);
            RETURN;
        END

        UPDATE dbo.COUPONS
        SET IS_DELETED = 1,
            DELETED_AT = SYSUTCDATETIME(),
            UPDATED_BY = @ACTIONED_BY
        WHERE COUPON_ID = @COUPON_ID;
    END
    ELSE
    BEGIN
        RAISERROR('Invalid operation mode. Supported modes: ADD, EDIT, DELETE.', 16, 1);
        RETURN;
    END

    -- Return the affected/created record
    SELECT 
        c.COUPON_ID AS CouponId,
        c.COUPON_CODE AS CouponCode,
        c.DISCOUNT_TYPE AS DiscountType,
        c.DISCOUNT_VALUE AS DiscountValue,
        c.MAX_DISCOUNT_AMOUNT AS MaxDiscountAmount,
        c.MINIMUM_ORDER_AMOUNT AS MinimumOrderAmount,
        c.VALID_FROM AS ValidFrom,
        c.VALID_TO AS ValidTo,
        c.USAGE_LIMIT_TOTAL AS UsageLimitTotal,
        c.USAGE_LIMIT_PER_USER AS UsageLimitPerUser,
        c.COUPON_STATUS AS CouponStatus,
        c.COUPON_DESC AS CouponDesc,
        c.CREATED_AT AS CreatedAt,
        c.UPDATED_AT AS UpdatedAt
    FROM dbo.COUPONS c
    WHERE c.COUPON_ID = @COUPON_ID;
END;
GO

-- 3. Update dbo.PR_GET_COUPONS Stored Procedure
CREATE OR ALTER PROCEDURE dbo.PR_GET_COUPONS
    @COUPON_ID              BIGINT = NULL,
    @COUPON_CODE            VARCHAR(50) = NULL,
    @COUPON_STATUS          VARCHAR(20) = NULL,
    @SEARCH                 NVARCHAR(150) = NULL,
    @PAGE_NUMBER            INT = 1,
    @PAGE_SIZE              INT = 10
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(1) AS TotalRecords  
    FROM dbo.COUPONS c 
    WHERE c.IS_DELETED = 0
    AND (@COUPON_ID IS NULL OR c.COUPON_ID = @COUPON_ID)
    AND (@COUPON_CODE IS NULL OR c.COUPON_CODE = @COUPON_CODE)
    AND (@COUPON_STATUS IS NULL OR c.COUPON_STATUS = @COUPON_STATUS)
    AND (@SEARCH IS NULL OR c.COUPON_CODE LIKE '%' + @SEARCH + '%' OR c.COUPON_DESC LIKE '%' + @SEARCH + '%');

    SELECT  
        c.COUPON_ID AS CouponId,
        c.COUPON_CODE AS CouponCode,
        c.DISCOUNT_TYPE AS DiscountType,
        c.DISCOUNT_VALUE AS DiscountValue,
        c.MAX_DISCOUNT_AMOUNT AS MaxDiscountAmount,
        c.MINIMUM_ORDER_AMOUNT AS MinimumOrderAmount,
        c.VALID_FROM AS ValidFrom,
        c.VALID_TO AS ValidTo,
        c.USAGE_LIMIT_TOTAL AS UsageLimitTotal,
        c.USAGE_LIMIT_PER_USER AS UsageLimitPerUser,
        c.COUPON_STATUS AS CouponStatus,
        c.COUPON_DESC AS CouponDesc,
        c.CREATED_AT AS CreatedAt,
        c.UPDATED_AT AS UpdatedAt
    FROM dbo.COUPONS c
    WHERE c.IS_DELETED = 0
    AND (@COUPON_ID IS NULL OR c.COUPON_ID = @COUPON_ID)
    AND (@COUPON_CODE IS NULL OR c.COUPON_CODE = @COUPON_CODE)
    AND (@COUPON_STATUS IS NULL OR c.COUPON_STATUS = @COUPON_STATUS)
    AND (@SEARCH IS NULL OR c.COUPON_CODE LIKE '%' + @SEARCH + '%' OR c.COUPON_DESC LIKE '%' + @SEARCH + '%')
    ORDER BY c.CREATED_AT DESC, c.COUPON_ID DESC
    OFFSET (@PAGE_NUMBER - 1) * @PAGE_SIZE ROWS
    FETCH NEXT @PAGE_SIZE ROWS ONLY;
END;
GO
