-- =============================================================================
-- MIGRATION SCRIPT 0148: Seed Default Active Coupons
-- =============================================================================

IF NOT EXISTS (SELECT 1 FROM dbo.COUPONS WHERE COUPON_CODE = 'SAVE15')
BEGIN
    INSERT INTO dbo.COUPONS
    (
        COUPON_CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, MAX_DISCOUNT_AMOUNT,
        MINIMUM_ORDER_AMOUNT, VALID_FROM, VALID_TO, USAGE_LIMIT_TOTAL,
        USAGE_LIMIT_PER_USER, COUPON_STATUS, COUPON_DESC, CREATED_AT, IS_DELETED
    )
    VALUES
    (
        'SAVE15', 'PERCENTAGE', 15.00, 50.00,
        20.00, '2026-01-01 00:00:00', '2030-12-31 23:59:59', 1000,
        5, 'ACTIVE', '15% Off Your Order (Up to 50 AED)', SYSUTCDATETIME(), 0
    );
END;

IF NOT EXISTS (SELECT 1 FROM dbo.COUPONS WHERE COUPON_CODE = 'WELCOME10')
BEGIN
    INSERT INTO dbo.COUPONS
    (
        COUPON_CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, MAX_DISCOUNT_AMOUNT,
        MINIMUM_ORDER_AMOUNT, VALID_FROM, VALID_TO, USAGE_LIMIT_TOTAL,
        USAGE_LIMIT_PER_USER, COUPON_STATUS, COUPON_DESC, CREATED_AT, IS_DELETED
    )
    VALUES
    (
        'WELCOME10', 'PERCENTAGE', 10.00, 30.00,
        15.00, '2026-01-01 00:00:00', '2030-12-31 23:59:59', 5000,
        1, 'ACTIVE', 'Welcome 10% Discount for New Customers', SYSUTCDATETIME(), 0
    );
END;

IF NOT EXISTS (SELECT 1 FROM dbo.COUPONS WHERE COUPON_CODE = 'PROMO10')
BEGIN
    INSERT INTO dbo.COUPONS
    (
        COUPON_CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, MAX_DISCOUNT_AMOUNT,
        MINIMUM_ORDER_AMOUNT, VALID_FROM, VALID_TO, USAGE_LIMIT_TOTAL,
        USAGE_LIMIT_PER_USER, COUPON_STATUS, COUPON_DESC, CREATED_AT, IS_DELETED
    )
    VALUES
    (
        'PROMO10', 'FLAT', 10.00, NULL,
        30.00, '2026-01-01 00:00:00', '2030-12-31 23:59:59', 1000,
        3, 'ACTIVE', 'Flat 10 AED Off Promo Code', SYSUTCDATETIME(), 0
    );
END;

IF NOT EXISTS (SELECT 1 FROM dbo.COUPONS WHERE COUPON_CODE = 'ALAZIMA20')
BEGIN
    INSERT INTO dbo.COUPONS
    (
        COUPON_CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, MAX_DISCOUNT_AMOUNT,
        MINIMUM_ORDER_AMOUNT, VALID_FROM, VALID_TO, USAGE_LIMIT_TOTAL,
        USAGE_LIMIT_PER_USER, COUPON_STATUS, COUPON_DESC, CREATED_AT, IS_DELETED
    )
    VALUES
    (
        'ALAZIMA20', 'PERCENTAGE', 20.00, 100.00,
        50.00, '2026-01-01 00:00:00', '2030-12-31 23:59:59', 500,
        2, 'ACTIVE', 'Al Azima Special 20% Discount', SYSUTCDATETIME(), 0
    );
END;
GO
