-- Migration: 0150_Create_Offers_And_Offer_Scopes_Table_And_Procedures.sql

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OFFERS]') AND type in (N'U'))
BEGIN
    CREATE TABLE dbo.OFFERS
    (
        OFFER_ID             BIGINT IDENTITY(1,1) NOT NULL,
        OFFER_TITLE_EN       NVARCHAR(200) NOT NULL,
        OFFER_TITLE_AR       NVARCHAR(200) NOT NULL,
        DISCOUNT_TYPE        NVARCHAR(50) NOT NULL, -- FLAT, PERCENTAGE
        DISCOUNT_VALUE       DECIMAL(18,2) NOT NULL,
        MINIMUM_ORDER_AMOUNT DECIMAL(18,2) NULL,
        MAX_DISCOUNT_AMOUNT  DECIMAL(18,2) NULL,
        START_AT             DATETIME2 NOT NULL,
        END_AT               DATETIME2 NOT NULL,
        IS_ACTIVE            BIT NOT NULL DEFAULT(1),
        CREATED_BY           BIGINT NULL,
        CREATED_AT           DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
        UPDATED_BY           BIGINT NULL,
        UPDATED_AT           DATETIME2 NULL,
        IS_DELETED           BIT NOT NULL DEFAULT(0),
        DELETED_AT           DATETIME2 NULL,
        CONSTRAINT PK_OFFERS PRIMARY KEY CLUSTERED (OFFER_ID ASC)
    );
END;
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OFFER_SCOPES]') AND type in (N'U'))
BEGIN
    CREATE TABLE dbo.OFFER_SCOPES
    (
        SCOPE_ID    BIGINT IDENTITY(1,1) NOT NULL,
        OFFER_ID    BIGINT NOT NULL,
        SCOPE_TYPE  NVARCHAR(50) NOT NULL, -- ALL, CATEGORY, PRODUCT
        CATEGORY_ID BIGINT NULL,
        PRODUCT_ID  BIGINT NULL,
        CREATED_AT  DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_OFFER_SCOPES PRIMARY KEY CLUSTERED (SCOPE_ID ASC),
        CONSTRAINT FK_OFFER_SCOPES_OFFERS FOREIGN KEY (OFFER_ID) REFERENCES dbo.OFFERS (OFFER_ID) ON DELETE CASCADE,
        CONSTRAINT FK_OFFER_SCOPES_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES dbo.CATEGORIES (CATEGORY_ID),
        CONSTRAINT FK_OFFER_SCOPES_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES dbo.PRODUCTS (PRODUCT_ID)
    );
END;
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_OFFER_SCOPE_CATEGORY' AND object_id = OBJECT_ID('dbo.OFFER_SCOPES'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_OFFER_SCOPE_CATEGORY 
    ON dbo.OFFER_SCOPES (OFFER_ID, CATEGORY_ID) 
    WHERE CATEGORY_ID IS NOT NULL;
END;
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_OFFER_SCOPE_PRODUCT' AND object_id = OBJECT_ID('dbo.OFFER_SCOPES'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_OFFER_SCOPE_PRODUCT 
    ON dbo.OFFER_SCOPES (OFFER_ID, PRODUCT_ID) 
    WHERE PRODUCT_ID IS NOT NULL;
END;
GO

CREATE OR ALTER PROCEDURE dbo.PR_SAVE_OFFER
    @MODE                 NVARCHAR(10),
    @OFFER_ID             BIGINT = NULL,
    @OFFER_TITLE_EN       NVARCHAR(200) = NULL,
    @OFFER_TITLE_AR       NVARCHAR(200) = NULL,
    @DISCOUNT_TYPE        NVARCHAR(50) = NULL,
    @DISCOUNT_VALUE       DECIMAL(18,2) = NULL,
    @MINIMUM_ORDER_AMOUNT DECIMAL(18,2) = NULL,
    @MAX_DISCOUNT_AMOUNT  DECIMAL(18,2) = NULL,
    @START_AT             DATETIME2 = NULL,
    @END_AT               DATETIME2 = NULL,
    @IS_ACTIVE            BIT = 1,
    @SCOPES_JSON          NVARCHAR(MAX) = NULL,
    @ACTIONED_BY          BIGINT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF UPPER(@MODE) = 'ADD'
    BEGIN
        INSERT INTO dbo.OFFERS
        (
            OFFER_TITLE_EN, OFFER_TITLE_AR, DISCOUNT_TYPE, DISCOUNT_VALUE,
            MINIMUM_ORDER_AMOUNT, MAX_DISCOUNT_AMOUNT, START_AT, END_AT,
            IS_ACTIVE, CREATED_BY, CREATED_AT, IS_DELETED
        )
        VALUES
        (
            @OFFER_TITLE_EN, @OFFER_TITLE_AR, UPPER(@DISCOUNT_TYPE), @DISCOUNT_VALUE,
            @MINIMUM_ORDER_AMOUNT, @MAX_DISCOUNT_AMOUNT, @START_AT, @END_AT,
            ISNULL(@IS_ACTIVE, 1), @ACTIONED_BY, SYSUTCDATETIME(), 0
        );

        SET @OFFER_ID = SCOPE_IDENTITY();
    END
    ELSE IF UPPER(@MODE) = 'EDIT'
    BEGIN
        UPDATE dbo.OFFERS
        SET OFFER_TITLE_EN       = ISNULL(@OFFER_TITLE_EN, OFFER_TITLE_EN),
            OFFER_TITLE_AR       = ISNULL(@OFFER_TITLE_AR, OFFER_TITLE_AR),
            DISCOUNT_TYPE        = ISNULL(UPPER(@DISCOUNT_TYPE), DISCOUNT_TYPE),
            DISCOUNT_VALUE       = ISNULL(@DISCOUNT_VALUE, DISCOUNT_VALUE),
            MINIMUM_ORDER_AMOUNT = @MINIMUM_ORDER_AMOUNT,
            MAX_DISCOUNT_AMOUNT  = @MAX_DISCOUNT_AMOUNT,
            START_AT             = ISNULL(@START_AT, START_AT),
            END_AT               = ISNULL(@END_AT, END_AT),
            IS_ACTIVE            = ISNULL(@IS_ACTIVE, IS_ACTIVE),
            UPDATED_BY           = @ACTIONED_BY,
            UPDATED_AT           = SYSUTCDATETIME()
        WHERE OFFER_ID = @OFFER_ID AND IS_DELETED = 0;
    END
    ELSE IF UPPER(@MODE) = 'DELETE'
    BEGIN
        UPDATE dbo.OFFERS
        SET IS_DELETED = 1,
            DELETED_AT = SYSUTCDATETIME(),
            UPDATED_BY = @ACTIONED_BY
        WHERE OFFER_ID = @OFFER_ID AND IS_DELETED = 0;

        SELECT @OFFER_ID AS OfferId;
        RETURN;
    END

    IF @SCOPES_JSON IS NOT NULL AND ISJSON(@SCOPES_JSON) = 1 AND @OFFER_ID IS NOT NULL
    BEGIN
        DELETE FROM dbo.OFFER_SCOPES WHERE OFFER_ID = @OFFER_ID;

        INSERT INTO dbo.OFFER_SCOPES (OFFER_ID, SCOPE_TYPE, CATEGORY_ID, PRODUCT_ID)
        SELECT 
            @OFFER_ID,
            UPPER(j.ScopeType),
            j.CategoryId,
            j.ProductId
        FROM OPENJSON(@SCOPES_JSON) WITH (
            ScopeType  NVARCHAR(50) '$.ScopeType',
            CategoryId BIGINT       '$.CategoryId',
            ProductId  BIGINT       '$.ProductId'
        ) j;
    END

    SELECT @OFFER_ID AS OfferId;
END;
GO

CREATE OR ALTER PROCEDURE dbo.PR_GET_OFFERS
    @OFFER_ID      BIGINT = NULL,
    @DISCOUNT_TYPE NVARCHAR(50) = NULL,
    @SEARCH        NVARCHAR(200) = NULL,
    @IS_ACTIVE     BIT = NULL,
    @PAGE_NUMBER   INT = 1,
    @PAGE_SIZE     INT = 10
AS
BEGIN
    SET NOCOUNT ON;

    SET @PAGE_NUMBER = ISNULL(@PAGE_NUMBER, 1);
    IF @PAGE_NUMBER < 1 SET @PAGE_NUMBER = 1;

    SET @PAGE_SIZE = ISNULL(@PAGE_SIZE, 10);
    IF @PAGE_SIZE < 1 SET @PAGE_SIZE = 10;

    SET @SEARCH = NULLIF(LTRIM(RTRIM(@SEARCH)), '');

    SELECT COUNT(1) AS TotalRecords
    FROM dbo.OFFERS o
    WHERE o.IS_DELETED = 0
      AND (@OFFER_ID IS NULL OR o.OFFER_ID = @OFFER_ID)
      AND (@DISCOUNT_TYPE IS NULL OR o.DISCOUNT_TYPE = UPPER(@DISCOUNT_TYPE))
      AND (@IS_ACTIVE IS NULL OR o.IS_ACTIVE = @IS_ACTIVE)
      AND (@SEARCH IS NULL OR o.OFFER_TITLE_EN LIKE '%' + @SEARCH + '%' OR o.OFFER_TITLE_AR LIKE '%' + @SEARCH + '%');

    SELECT 
        o.OFFER_ID AS OfferId,
        o.OFFER_TITLE_EN AS OfferTitleEn,
        o.OFFER_TITLE_AR AS OfferTitleAr,
        o.DISCOUNT_TYPE AS DiscountType,
        o.DISCOUNT_VALUE AS DiscountValue,
        o.MINIMUM_ORDER_AMOUNT AS MinimumOrderAmount,
        o.MAX_DISCOUNT_AMOUNT AS MaxDiscountAmount,
        o.START_AT AS StartAt,
        o.END_AT AS EndAt,
        o.IS_ACTIVE AS IsActive,
        o.CREATED_AT AS CreatedAt,
        o.UPDATED_AT AS UpdatedAt
    FROM dbo.OFFERS o
    WHERE o.IS_DELETED = 0
      AND (@OFFER_ID IS NULL OR o.OFFER_ID = @OFFER_ID)
      AND (@DISCOUNT_TYPE IS NULL OR o.DISCOUNT_TYPE = UPPER(@DISCOUNT_TYPE))
      AND (@IS_ACTIVE IS NULL OR o.IS_ACTIVE = @IS_ACTIVE)
      AND (@SEARCH IS NULL OR o.OFFER_TITLE_EN LIKE '%' + @SEARCH + '%' OR o.OFFER_TITLE_AR LIKE '%' + @SEARCH + '%')
    ORDER BY o.CREATED_AT DESC, o.OFFER_ID DESC
    OFFSET (@PAGE_NUMBER - 1) * @PAGE_SIZE ROWS
    FETCH NEXT @PAGE_SIZE ROWS ONLY;

    SELECT 
        s.SCOPE_ID AS ScopeId,
        s.OFFER_ID AS OfferId,
        s.SCOPE_TYPE AS ScopeType,
        s.CATEGORY_ID AS CategoryId,
        c.CATEGORY_NAME_EN AS CategoryNameEn,
        s.PRODUCT_ID AS ProductId,
        p.PRODUCT_NAME_EN AS ProductNameEn
    FROM dbo.OFFER_SCOPES s
    INNER JOIN dbo.OFFERS o ON s.OFFER_ID = o.OFFER_ID
    LEFT JOIN dbo.CATEGORIES c ON s.CATEGORY_ID = c.CATEGORY_ID
    LEFT JOIN dbo.PRODUCTS p ON s.PRODUCT_ID = p.PRODUCT_ID
    WHERE o.IS_DELETED = 0
      AND (@OFFER_ID IS NULL OR o.OFFER_ID = @OFFER_ID)
      AND (@DISCOUNT_TYPE IS NULL OR o.DISCOUNT_TYPE = UPPER(@DISCOUNT_TYPE))
      AND (@IS_ACTIVE IS NULL OR o.IS_ACTIVE = @IS_ACTIVE)
      AND (@SEARCH IS NULL OR o.OFFER_TITLE_EN LIKE '%' + @SEARCH + '%' OR o.OFFER_TITLE_AR LIKE '%' + @SEARCH + '%');
END;
GO

CREATE OR ALTER PROCEDURE dbo.PR_GET_ACTIVE_OFFERS
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @NOW DATETIME2 = SYSUTCDATETIME();

    SELECT 
        o.OFFER_ID AS OfferId,
        o.OFFER_TITLE_EN AS OfferTitleEn,
        o.OFFER_TITLE_AR AS OfferTitleAr,
        o.DISCOUNT_TYPE AS DiscountType,
        o.DISCOUNT_VALUE AS DiscountValue,
        o.MINIMUM_ORDER_AMOUNT AS MinimumOrderAmount,
        o.MAX_DISCOUNT_AMOUNT AS MaxDiscountAmount,
        o.START_AT AS StartAt,
        o.END_AT AS EndAt,
        o.IS_ACTIVE AS IsActive
    FROM dbo.OFFERS o
    WHERE o.IS_DELETED = 0
      AND o.IS_ACTIVE = 1
      AND @NOW BETWEEN o.START_AT AND o.END_AT
    ORDER BY o.CREATED_AT DESC;

    SELECT 
        s.SCOPE_ID AS ScopeId,
        s.OFFER_ID AS OfferId,
        s.SCOPE_TYPE AS ScopeType,
        s.CATEGORY_ID AS CategoryId,
        c.CATEGORY_NAME_EN AS CategoryNameEn,
        s.PRODUCT_ID AS ProductId,
        p.PRODUCT_NAME_EN AS ProductNameEn
    FROM dbo.OFFER_SCOPES s
    INNER JOIN dbo.OFFERS o ON s.OFFER_ID = o.OFFER_ID
    LEFT JOIN dbo.CATEGORIES c ON s.CATEGORY_ID = c.CATEGORY_ID
    LEFT JOIN dbo.PRODUCTS p ON s.PRODUCT_ID = p.PRODUCT_ID
    WHERE o.IS_DELETED = 0
      AND o.IS_ACTIVE = 1
      AND @NOW BETWEEN o.START_AT AND o.END_AT;
END;
GO
