CREATE TABLE dbo.Settings
(
    SettingId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    SettingKey NVARCHAR(150) NOT NULL UNIQUE,
    SettingValue NVARCHAR(MAX) NULL,
    Category NVARCHAR(100) NULL,
    Description NVARCHAR(500) NULL,
    IsEncrypted BIT NOT NULL DEFAULT 0,
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedOn DATETIME2 NULL
);