CREATE TABLE dbo.Permissions
(
    PermissionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    PermissionCode NVARCHAR(150) NOT NULL UNIQUE,
    PermissionName NVARCHAR(200) NOT NULL,
    Module NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NULL,
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);