CREATE TABLE dbo.UserSessions
(
    SessionId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    RefreshToken NVARCHAR(500) NULL,
    IpAddress NVARCHAR(50) NULL,
    UserAgent NVARCHAR(1000) NULL,
    LoginTime DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ExpiresOn DATETIME2 NOT NULL,
    RevokedOn DATETIME2 NULL,
    IsActive AS (CASE WHEN RevokedOn IS NULL AND ExpiresOn > SYSUTCDATETIME() THEN 1 ELSE 0 END),
    CONSTRAINT FK_UserSessions_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId)
);