CREATE TABLE dbo.ApiClients
(
    ClientId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    ClientName NVARCHAR(200) NOT NULL,
    ClientKey NVARCHAR(200) NOT NULL UNIQUE,
    ClientSecretHash NVARCHAR(MAX) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    LastUsedOn DATETIME2 NULL,
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);