CREATE TABLE dbo.AuditLogs
(
    AuditLogId BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NULL,
    TableName NVARCHAR(200) NOT NULL,
    RecordId NVARCHAR(200) NOT NULL,
    OperationType NVARCHAR(20) NOT NULL,
    OldValues NVARCHAR(MAX) NULL,
    NewValues NVARCHAR(MAX) NULL,
    IpAddress NVARCHAR(50) NULL,
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);