CREATE TABLE dbo.ActivityLogs
(
    ActivityLogId BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NULL,
    ActivityType NVARCHAR(100) NOT NULL,
    Description NVARCHAR(1000) NOT NULL,
    Source NVARCHAR(100) NULL,
    ReferenceId NVARCHAR(200) NULL,
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);