CREATE TABLE dbo.ErrorLogs
(
    ErrorLogId BIGINT IDENTITY(1,1) PRIMARY KEY,
    ErrorMessage NVARCHAR(MAX) NOT NULL,
    StackTrace NVARCHAR(MAX) NULL,
    Source NVARCHAR(500) NULL,
    RequestPath NVARCHAR(500) NULL,
    UserId UNIQUEIDENTIFIER NULL,
    LoggedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);