CREATE TABLE dbo.BackgroundJobs
(
    JobId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    JobName NVARCHAR(200) NOT NULL,
    JobType NVARCHAR(200) NOT NULL,
    Payload NVARCHAR(MAX) NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    ScheduledOn DATETIME2 NOT NULL,
    StartedOn DATETIME2 NULL,
    CompletedOn DATETIME2 NULL,
    ErrorMessage NVARCHAR(MAX) NULL,
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);