CREATE TABLE dbo.SystemNotifications
(
    NotificationId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    NotificationType NVARCHAR(50) NOT NULL,
    Severity NVARCHAR(20) NOT NULL DEFAULT 'Info',
    IsRead BIT NOT NULL DEFAULT 0,
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ReadOn DATETIME2 NULL
);