-- Migration 0034: Create Updated Auth Tables (USERS, ROLES, USER_ROLES, OTP_VERIFICATIONS, USER_SESSIONS)

-- If legacy USERS table exists (without USER_ID column), drop all legacy auth foreign keys & tables dynamically
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'USERS') 
   AND NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.USERS') AND name = 'USER_ID')
BEGIN
    DECLARE @dropFksSql NVARCHAR(MAX) = N'';
    SELECT @dropFksSql += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + 
                          N' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13)
    FROM sys.foreign_keys
    WHERE referenced_object_id IN (OBJECT_ID('dbo.USERS'), OBJECT_ID('dbo.ROLES'), OBJECT_ID('dbo.USER_ROLES'), OBJECT_ID('dbo.ROLE_PERMISSIONS'), OBJECT_ID('dbo.USER_SESSIONS'), OBJECT_ID('dbo.REFRESH_TOKENS'))
       OR parent_object_id IN (OBJECT_ID('dbo.USERS'), OBJECT_ID('dbo.ROLES'), OBJECT_ID('dbo.USER_ROLES'), OBJECT_ID('dbo.ROLE_PERMISSIONS'), OBJECT_ID('dbo.USER_SESSIONS'), OBJECT_ID('dbo.REFRESH_TOKENS'));
    
    IF @dropFksSql <> N''
        EXEC sp_executesql @dropFksSql;

    IF EXISTS (SELECT * FROM sys.tables WHERE name = 'REFRESH_TOKENS') EXEC sp_executesql N'DROP TABLE dbo.REFRESH_TOKENS;';
    IF EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_SESSIONS') EXEC sp_executesql N'DROP TABLE dbo.USER_SESSIONS;';
    IF EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_ROLES') EXEC sp_executesql N'DROP TABLE dbo.USER_ROLES;';
    IF EXISTS (SELECT * FROM sys.tables WHERE name = 'ROLE_PERMISSIONS') EXEC sp_executesql N'DROP TABLE dbo.ROLE_PERMISSIONS;';
    IF EXISTS (SELECT * FROM sys.tables WHERE name = 'USERS') EXEC sp_executesql N'DROP TABLE dbo.USERS;';
    IF EXISTS (SELECT * FROM sys.tables WHERE name = 'ROLES') EXEC sp_executesql N'DROP TABLE dbo.ROLES;';
END

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ROLES')
BEGIN
    CREATE TABLE dbo.ROLES
    (
        ROLE_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ROLE_CODE VARCHAR(50) NOT NULL UNIQUE,
        ROLE_NAME VARCHAR(100) NOT NULL,
        DESCRIPTION VARCHAR(500) NULL,
        IS_ACTIVE BIT NOT NULL DEFAULT 1,
        CREATED_AT DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT DATETIME2 NULL
    );
END

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USERS')
BEGIN
    CREATE TABLE dbo.USERS
    (
        USER_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        COUNTRY_CODE VARCHAR(10) NOT NULL,
        MOBILE_NUMBER VARCHAR(20) NOT NULL,
        EMAIL VARCHAR(150) NULL,
        PASSWORD_HASH VARCHAR(500) NULL,
        FULL_NAME NVARCHAR(150) NOT NULL,
        PROFILE_IMAGE_URL VARCHAR(500) NULL,
        DESIGNATION NVARCHAR(100) NULL,
        LANGUAGE_CODE VARCHAR(10) NOT NULL DEFAULT 'EN',
        IS_MOBILE_VERIFIED BIT NOT NULL DEFAULT 0,
        IS_EMAIL_VERIFIED BIT NOT NULL DEFAULT 0,
        IS_PROFILE_COMPLETED BIT NOT NULL DEFAULT 0,
        USER_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
        LAST_LOGIN_AT DATETIME2 NULL,
        CREATED_AT DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT DATETIME2 NULL,
        CONSTRAINT UQ_USERS_MOBILE UNIQUE (COUNTRY_CODE, MOBILE_NUMBER)
    );

    CREATE UNIQUE NONCLUSTERED INDEX UQ_USERS_EMAIL 
    ON dbo.USERS(EMAIL) 
    WHERE EMAIL IS NOT NULL;
END

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_ROLES')
BEGIN
    CREATE TABLE dbo.USER_ROLES
    (
        USER_ROLE_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USER_ID BIGINT NOT NULL,
        ROLE_ID INT NOT NULL,
        IS_ACTIVE BIT NOT NULL DEFAULT 1,
        ASSIGNED_AT DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        ASSIGNED_BY_USER_ID BIGINT NULL,
        UPDATED_AT DATETIME2 NULL,
        CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES dbo.USERS(USER_ID),
        CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES dbo.ROLES(ROLE_ID),
        CONSTRAINT FK_USER_ROLES_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY_USER_ID) REFERENCES dbo.USERS(USER_ID),
        CONSTRAINT UQ_USER_ROLES UNIQUE (USER_ID, ROLE_ID)
    );
END

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'OTP_VERIFICATIONS')
BEGIN
    CREATE TABLE dbo.OTP_VERIFICATIONS
    (
        OTP_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USER_ID BIGINT NULL,
        COUNTRY_CODE VARCHAR(10) NOT NULL,
        MOBILE_NUMBER VARCHAR(20) NOT NULL,
        OTP_HASH VARCHAR(500) NOT NULL,
        OTP_PURPOSE VARCHAR(30) NOT NULL,
        ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
        RESEND_COUNT INT NOT NULL DEFAULT 0,
        MAX_ATTEMPTS INT NOT NULL DEFAULT 5,
        OTP_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
        EXPIRES_AT DATETIME2 NOT NULL,
        VERIFIED_AT DATETIME2 NULL,
        CREATED_AT DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT DATETIME2 NULL,
        CONSTRAINT FK_OTP_VERIFICATIONS_USER FOREIGN KEY (USER_ID) REFERENCES dbo.USERS(USER_ID)
    );

    CREATE NONCLUSTERED INDEX IX_OTP_VERIFICATIONS_MOBILE 
    ON dbo.OTP_VERIFICATIONS(COUNTRY_CODE, MOBILE_NUMBER, OTP_STATUS);
END

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_SESSIONS')
BEGIN
    CREATE TABLE dbo.USER_SESSIONS
    (
        SESSION_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USER_ID BIGINT NOT NULL,
        REFRESH_TOKEN_HASH VARCHAR(500) NOT NULL,
        DEVICE_ID VARCHAR(200) NULL,
        DEVICE_TYPE VARCHAR(30) NULL,
        IP_ADDRESS VARCHAR(45) NULL,
        IS_ACTIVE BIT NOT NULL DEFAULT 1,
        EXPIRES_AT DATETIME2 NOT NULL,
        LAST_ACTIVITY_AT DATETIME2 NULL,
        CREATED_AT DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UPDATED_AT DATETIME2 NULL,
        CONSTRAINT FK_USER_SESSIONS_USER FOREIGN KEY (USER_ID) REFERENCES dbo.USERS(USER_ID)
    );

    CREATE NONCLUSTERED INDEX IX_USER_SESSIONS_USER_ACTIVE 
    ON dbo.USER_SESSIONS(USER_ID, IS_ACTIVE);
END
